### ISSUE TITLE
Export `ordiArrowMul()`

### ISSUE THREAD

**Issue by gavinsimpson** [vegandevs/vegan#102]
Would there be any objection to exporting the currently internal function `ordiArrowMul()`? **ggvegan** makes use of this to rescale arrows in (tri|bi)plots of constrained ordinations. I'm currently accessing this as `vegan:::ordiArrowMul` but `R CMD check` complains about this usage as a Note.

If it's not suitable for export in its current form, what would be required before we'd be happy exporting it?

**Comment by jarioksa** [comment]
Gav,

It is quite OK to export ordiArrowMul. It was not exported because I thought it was not so interesting to the users, but actually we tell how to use it in docs so that we also could export it.

NB, we use now ordiArrowTextXY to calculate the coordinates of text labels at the tip of the arrow. Should this be exported, too?

Cheers, Jari

**Comment by gavinsimpson** [comment]
Great. I'll work on that, and I do think it would be useful to export `ordiArrowTextXY` - I wonder what I am doing to add text labels to arrows in **ggvegan**...?

I'll self-assign this to me and work through the details.

**Comment by jarioksa** [comment]
I merged PR #107. However, there are a couple of things to do after this:

I moved the `ordiArrow*` documentations from `man/ordiarrows.Rd` to `man/envfit.Rd` in commit 24776d6b4. Despite similarity of names, `ordiarrows()` function is unrelated to `ordiArrow*` functions. The `ordiArrow*` functions are only used in `plot.envfit()` and `plot.cca` and their friends, and the functions should be documented with these. However, I think that the current example may be a bit long and technical in the context of `envfit`  documentation. 

The `ordiArrow*`  functions were internal functions, and therefore they are not user-friendly: we assume that calling functions take care that calls to internal functions are absolutely correct. If we let loose these functions, we should add some elements of usability. I think the minimal thing is that the input data `x`  can also be an ordination object or an `envfit` object, and `ordiArrowMul`  can extract the scores and `ordiArrowTextXY` can extract the scores and labels from this object. This could happen by adding `x <- scores(x, dis="sites", ...)` to these functions.

**Comment by jarioksa** [comment]
It perhaps makes sense to separate `ordiArrow*` documentation into its own `Rd` page. This would allow nerdier description and examples but reduce clutter in `man/envfit.Rd`. I think `envfit()` is an entry-level function which should be explained in simple terms, and technical details should be explained somewhere else. 

Just my €0.02.

**Comment by gavinsimpson** [comment]
@jarioksa agreed. I wanted to export this and then see about improving it as a more robustified function for general usage. I was also unsure where to document this and went with something that was at least similar *in spirit*.

I'm travelling this week so should have some time to work on this.

**Comment by jarioksa** [comment]
Closed with PR #114
