### ISSUE TITLE
Calculating Shannon's equitability? 

### ISSUE THREAD

**Issue by deepthoughts** [vegandevs/vegan#111]
Can we add function to calculate Shannon's equitability? It can be added along with the diversity index option. 
![shannondi eqn2](https://cloud.githubusercontent.com/assets/3029968/7496061/98daa1f2-f3d7-11e4-84c1-12de8c3ff9db.gif)

**Comment by jarioksa** [comment]
Do you really need a function for this? You can use directly:
```R
library(vegan)
data(mite)
diversity(mite)/log(specnumber(mite))
```

**Comment by deepthoughts** [comment]
Thank you. Definitely lot easier than I thought.
