### ISSUE TITLE
Allow more control over colours / groups for plot.betadisper

### ISSUE THREAD

**Issue by gavinsimpson** [vegandevs/vegan#128]
Several of the drawn components of the `plot.betadisper()` output are hardcode. Allow users to specify vectors of colours for these elements.

**Comment by jarioksa** [comment]
Fine! Please do this.

**Comment by CarlyRae** [comment]
Hello,

I requested this during the Vegan workshop at ESA. I am trying to figure out which pch characters relate to which factor level in the plot.betadisper. 

It would be great to have some additional control over the plot that is created. 

For the time being could you tell me how to find out which pch is which group?

For instance, I did this 

mod2_ele <- betadisper(uni_ele, ele_group)
anova(mod2_ele)
plot(mod2_ele)

str(mod2_ele)

#### From str I can see the group order, but where can I find how the pch are specified? 

 $ group    : Factor w/ 4 levels "1000","700","800",..: 4 1 4 4 1 1 1 4 1 3 ...

Thanks and would love to see more features with this plotting function. The figures are informative.

**Comment by gavinsimpson** [comment]
@CarlyRae OK - I'll tackle this ahead of the release vegan version 2.4-0. We've only just started talking about this and there are a lot of candidates for inclusion in 2.4-0 so it might not be on CRAN for a while, but try to get some time to implement something for `plot.betadisper()` in the next week or two.

**Comment by CarlyRae** [comment]
Great, I look forward to seeing what you develop.

**Comment by jarioksa** [comment]
I think we are done with this after @gavinsimpson committed baea831
