### ISSUE TITLE
Release 2.3-1

### ISSUE THREAD

**Issue by jarioksa** [vegandevs/vegan#139]
Perhaps we should have a minor 2.3-1 release of **vegan**. The current devel branch `vegandevs/master` has some new features that need work & testing before release, mainly related to db-RDA, `adonis`  and `varpart` of dissimilarities. Some smaller changes and bug fixes have been cherry-picked to `cran-2.3` and we could pack that to a minor release. 

Main user-visible changes are listed in `inst/NEWS.Rd` (http://vegan.r-forge.r-project.org/NEWS.html). In addition, the `cran-2.3`  branch is adopted to new CRAN policy and no longer gives warnings in CRAN checks. I think the branch could be packed for release any day. However, there are some changes that still could be picked to the 2.3-1 release if wanted:

* PR #137 (user-friendly scaling in `cca` etc.) of @gavinsimpson : I haven't checked if this can be merged easily. This is a new feature and could be left to 2.4-0, but can be merged as well.
* PR #123 (`permustats.anova.cca`) of @EDiLD  is also a new feature that can be merged or left to 2.4-0. I have tested this in a `cran-2.3`  branch and I know that this can be merged after resolving a couple of conflicts by hand.
* PR #118 and PR #119 are best left out, because they can change the user interface. With these pull requests, `ordiellipse` and `ordihull`  will return also one-point "ellipses" and "hulls" whereas they were omitted in previous code. Therefore the items returned from these functions can change and this change could be left to 2.4-0.
* If we don't merge those PR's, we probably also need to leave #138 of @j-tweed to 2.4-0. PR #138 is not merged to `master` yet so that it is pretty young if we plan a quick release. There seem to be some conflicts with `cran-2.3`, but I haven't tested how easy these are to resolve.

I think all other things are so large that we won't have them in 2.3-1.

**Comment by jarioksa** [comment]
Nobody seems to be passionate about 2.3-1 release. If nothing new happens, I'll submit the current-ish version to CRAN non Monday Sep 14. The window of new merges closes by weekend.

I'll also submit a new version of **vegan3d**. There is one bug-fix (`orglspider` was not exported) plus adaptation to new CRAN policies.

**Comment by gavinsimpson** [comment]
Sorry I'm coming late to this; busy preparing to go into and then actually went into the field.

I'll deal with cherry-picking PR #137 changes into the `cran-2.3` branch.

**Comment by jarioksa** [comment]
OK. Take your time. I'm not in a hurry with the release. I was just thinking this is a nice quite spot before big things happen in `master`.

**Comment by jarioksa** [comment]
@gavinsimpson merged #137 to 2.3-1. After writing a NEWS message and running tests (including package tests), I head for the release. I hope to have the release by Friday 18/9/15.

The only open issue is the merger of  `permustats.anova.cca` which seems to be doable: I have a branch ready where I have solved the conflicts. What about this @EDiLD ?

**Comment by EDiLD** [comment]
#123 is a very small feature which shouldn't break anything or change for users.
If there are no problems i would release it - the earlier the better ;)

**Comment by jarioksa** [comment]
@EDiLD #123 now in 2.3-1. Scheduling CRAN submission tomorrow. ("Submission" is an adequate term when you're talking about CRAN).

**Comment by gavinsimpson** [comment]
@jarioksa I've merged the BCI env data changes into the `cran-2.3`. I'm not aware of anything else outstanding now, certainly not anything I wanted to squeeze in at this stage.

**Comment by jarioksa** [comment]
OK. I'll try to submit this asap.

Sent from my iPad

On 22.9.2015, at 19.42, Gavin Simpson <notifications@github.com<mailto:notifications@github.com>> wrote:


@jarioksa<https://github.com/jarioksa> I've merged the BCI env data changes into the cran-2.3. I'm not aware of anything else outstanding now, certainly not anything I wanted to squeeze in at this stage.

-

**Comment by jarioksa** [comment]
Submitted to CRAN today (tagged v2.3-1). Let us wait for the CRAN response.

**Comment by jarioksa** [comment]
Did not go straight through, but they sent a comment on this:
```
* checking R code for possible problems ... NOTE
Found the following assignments to the global environment:
File ‘vegan/R/orditkplot.R’:
 assign(dumpName, xy, envir = .GlobalEnv)
 assign(dumpName, xy, envir = .GlobalEnv)
```
I wrote about this in my submission notes, but it seems that it was overlooked. I sent a response. Let's see.
