### ISSUE TITLE
capscale.Rd missing quote

### ISSUE THREAD

**Issue by sethrfore** [vegandevs/vegan#143]
Add missing quote to capscale.Rd, line 236 solves compiling error for current dev version.

**Comment by gavinsimpson** [comment]
Thanks; now fixed with ba9eb91

**Comment by jarioksa** [comment]
It seems that I forgot to commit the fix from my office desktop where I did this (and another commit). Got to see if I got to resolve conflicts in my office desktop tomorrow.

**Comment by gavinsimpson** [comment]
Sorry @jarioksa; You are usually pretty quick at handling these things so I figured you were busy when this wasn't handled whilst I slept on the other side of the pond.

**Comment by jarioksa** [comment]
No worries @gavinsimpson , gives me time to rethink. Actually I believed I had already fixed this, but then I found out I hadn't pushed my fix to github. I was busy, too: had to update my Amborella knowledge for lectures.
