### ISSUE TITLE
Gower distance and negative values

### ISSUE THREAD

**Issue by plantarum** [vegandevs/vegan#146]
Hi,

When using vegdist for the Gower distance with negative values, a warning is issued: "results may be meaningless because data have negative entries in method Gower". I think this is misleading, as the Gower distance works just fine with negative values.

From the code I see all methods other than manhattan and euclidean get this treatment (`method > 2`). Perhaps `! method %in% c(1, 2, 6)` could be used here instead?

Best,

Tyler

**Comment by jarioksa** [comment]
Correct: warning is not needed. It also seems that methods `"altGower"` and `"mahalanobis"` can handle negative input data.

**Comment by jarioksa** [comment]
close with 57f73dd0
