### ISSUE TITLE
different results from vegan depending on input type

### ISSUE THREAD

**Issue by GSatten** [vegandevs/vegan#147]
i am trying to use the adonis function in vegan to run the permanova analysis.  but i am getting very different results depending on how i call adonis.

if i call adonis using a distance object such as the following:

bc=vegdist( data, method='bray')
adonis(bc~var)

i get a very different result than if i convert bc (a dist object) into a matrix:

bc=as.matrix( vegdist(data, method='bray') )
adonis(bc~var)

what is causing this difference and which is correct?

**Comment by jarioksa** [comment]
You should supply either a distance object or data. If you supply a matrix, it is regarded as data and dissimilarities are calculated. So the following should be equivalent:
```R
bc <- vegdist(data, method="bray")
adonis(bc ~ var)
adonis(data ~ var)
```
The second form you had would be equivalent to:
```R
adonis(vegdist(as.matrix(vegdist(data))) ~ var)
```
which makes no sense. I suggest you follow the document and supply either a distance object or data.
