### ISSUE TITLE
can orditorp accept other objects

### ISSUE THREAD

**Issue by romunov** [vegandevs/vegan#148]
Hi,

I'm [enhancing the `dapc` function](https://github.com/thibautjombart/adegenet/issues/100) in `adegenet` and I would like to use vegan's `orditorp` function for its superb positioning of labels. In [line 10 of the function](https://github.com/vegandevs/vegan/blob/master/R/orditorp.R#L10) scores are extracted. This is a minor set back for me since the object I get is of class `dapc` and there is no available method to extract scores from the object (yet) and I would like to avoid constructing the data into a fake class just for this step.

Would the dev team be willing to accept a minor modification to `orditorp` function in order to accept two column matrices, or even better, accept a pull-request for `scores.dapc`?

**Comment by gavinsimpson** [comment]
Isn't the simple solution one in which you just write a `scores` method for class `"dapc"` that you use locally, which does the extraction and arranging of the scores?

I don't think that **vegan** including a `scores.dapc` method is the right solution. I would have thought that **adegenet** would be the more useful place for this. That said, we do handle some objects created by **ade4**. I doubt we want **vegan** to include all manner of extractor functions for.

Also, `scores.default()` should work with a matrix of scores so there is little preventing use of `orditrop()`.

**Comment by romunov** [comment]
I agree.
