### ISSUE TITLE
bug? Error in scores.default...

### ISSUE THREAD

**Issue by fish06** [vegandevs/vegan#151]
Hi, I'm using vegan 2.3.2 and I want to extract the scores from a CCA by using:

>scores(cca1,choices=c(1,2),display="sites")

Strangely, it worked for the axes 2 and 3 (choices=c(2,3)) but when I tried with axes 1 and 2, it gave me the following error message:
 Error in scores.default(cca1, choices = c(1, 2), display = "sites") : 
  Can't find scores

I already re-installed vegan but I can't figure out the problem.
I guess it's bug.

Thanks for any help!

**Comment by jarioksa** [comment]
I can't reproduce this: the example (with my own `cca` result) works normally. Need more details to reproduce the problem.

**Comment by fish06** [comment]
Hi,

thanks for your fast reply! 
Strange enough but I can't reproduce it anymore, either.
I just restarted R another time and now it works!

Cheers

----------------------------------------------
Sunna Ellendt
PhD Student

Max Planck Institute for Evolutionary Biology
Evolutionary Genetics of Fishes
August-Thienemann Str. 2
24306 Plön, Germany
Tel: 04522 763 235

----- Ursprüngliche Mail -----
Von: "Jari Oksanen" <notifications@github.com>
An: "vegandevs/vegan" <vegan@noreply.github.com>
CC: "Sunna Ellendt" <ellendt@evolbio.mpg.de>
Gesendet: Dienstag, 8. Dezember 2015 18:56:10
Betreff: Re: [vegan] bug? Error in scores.default... (#151)

I can't reproduce this: the example (with my own `cca` result) works normally. Need more details to reproduce the problem.

---
