### ISSUE TITLE
Interest in adding r2-adjusted for CCA?

### ISSUE THREAD

**Issue by dmcglinn** [vegandevs/vegan#161]
Peres-Neto et al (2006) developed a permutation based method for computing an adjusted r2 for cca. I have code that can accomplish this that I would be happy to contribute to the package if there was any interest in adding it in. This would add functionality to the existing function `RsquareAdj`. 

Peres-Neto, P., P. Legendre, S. Dray and D. Borcard. 2006. Variation partitioning of species data matrices: estimation and comparison of fractions. Ecology 87, 2614–2625.

**Comment by gavinsimpson** [comment]
Hi Dan,

Yes, we'd like to see this in vegan, if only for consistency. Jari and I discussed this on and off in relation to some of my vegan slide decks but I never found the time to read the paper or do the implementation.

How do you want to go about this? If you don't want or have time to integrate this directly into vegan I'd be happy to take your code and get in into the package. Or you could do this yourself. I don't mind either way, whatever works best for you.

Thanks for this,

G

**Comment by jarioksa** [comment]
We really want to see this in vegan. Like Gav, I never had time to check how to do this in **vegan**, but we'd really like to have it there. With the latest changes, we also have `RsquareAdj` for db-RDA, and this would remove the last exception from constrained methods.

**Comment by gavinsimpson** [comment]
Closed via bbaf30d
