### ISSUE TITLE
distance to centroid from samples outside the group

### ISSUE THREAD

**Issue by ghanesh** [vegandevs/vegan#185]
Hello!
I am searching for a way to calculate the **distance** from **any** sample in a **Bray-Curtis metric** to a **group centroid.** 
With betadisper() I believe I am half way there, at least it is possible to calculate the centroids and distances to the contributing samples. But, I did not figure out a way to calculate the the distance to the other samples, not being part of that group, which would be a treat!
Thank you for your suggestions / help.

**Comment by ghanesh** [comment]
Using the dist() function on a combined dataset of centroids and samples in PCoA space seems to be working.

**Comment by NainaKhandelwal** [comment]
Hi Ghanesh. I'm trying to do the exact thing you described. Can you please detail the solution that worked? Not able to follow the combined dataset idea...

Thanks!

**Comment by gavinsimpson** [comment]
You can't use `dist()` for this if there are axes with negative eigenvalues; in that case you need to compute distances using the axes with positive eigenvalues separately from the axes with negative eigenvalues, and then subtract the negative-eigenvalue distances from the positive-eigenvalue distances. These steps are done in `betadisper()`

* Distances among axes with positive eigenvalues: https://github.com/vegandevs/vegan/blob/master/R/betadisper.R#L122-L123
* Distances among axes with positive eigenvalues, if any: https://github.com/vegandevs/vegan/blob/master/R/betadisper.R#L124-L127
* Compute final distance: https://github.com/vegandevs/vegan/blob/master/R/betadisper.R#L129
