### ISSUE TITLE
wcmdscale object

### ISSUE THREAD

**Issue by EDiLD** [vegandevs/vegan#186]
The `wcmdscale()` has a somewhat special output compared to all other ordination methods (rda, cca, dbrda, ...).
It returns either a matrix of scores or a list with more detailed information.

Would it be worth to adapt to be more similar to `cca.object`?  `eig` could be skipped completely...
I could try to write prototype...

**Comment by jarioksa** [comment]
The output is similar as in `stats::cmdscale()`. The function was designed as a drop-in replacement of standard `cmdscale`. Careful testing is needed if this similarity is broken.

**Comment by jarioksa** [comment]
FWIW, the function was deliberately changed to return only scores matrix with default options in e6c661f89ceaab182150ac8f19bb353105b3fc42
