### ISSUE TITLE
incorporate MARGIN parameter in rrarefy?

### ISSUE THREAD

**Issue by invertdna** [vegandevs/vegan#188]
Given that "wide" dataframes take up much more memory than "long" dataframes, I think it would be desirable to have the option to specify MARGIN=2 in the rrarefy command, to speed up handling of large datasets. Thanks.

**Comment by psolymos** [comment]
The `rrarefy` function has a line that makes a matrix out of any matrix-like input object `x`, including data frames (`x <- as.matrix(x)`). This means that transposing or adding a `MARGIN` argument is not really a solution here in my opinion. Community data can be more effectively stored in a matrix.

**Comment by jarioksa** [comment]
Timing with **microbenchmark** package does not support the claims here. Wide data frames may be a bit slower, but the only difference seems to be that `as.matrix`  is slower for wide data frames. Faster code would be accepted, though, but it must be proved to be faster in practice.
