### ISSUE TITLE
goodness.cca currently ignores choices argument

### ISSUE THREAD

**Issue by gavinsimpson** [vegandevs/vegan#190]
As mentioned in the discussion surrounding #189, the `choices` argument it not used in `goodness.cca`.

```r
library(vegan)
data(dune, dune.env)
goodness(cca(dune ~ A1 + Moisture + Manure, dune.env), choices = 2)
```

```rout
> head(goodness(cca(dune ~ A1 + Moisture + Manure, dune.env), choices = 2))
               CCA1      CCA2      CCA3      CCA4      CCA5      CCA6      CCA7
Achimill 0.33914782 0.4686996 0.5161329 0.5627598 0.6260376 0.6277621 0.6349226
Agrostol 0.47902756 0.6854956 0.6866681 0.6921161 0.7609479 0.7684217 0.7697606
Airaprae 0.03895767 0.2844500 0.3369202 0.4081454 0.4326753 0.4396726 0.4413921
Alopgeni 0.04957140 0.5630997 0.5761448 0.7128628 0.7331946 0.7332199 0.7334576
Anthodor 0.04059179 0.3099049 0.3245315 0.4196064 0.4915799 0.4945911 0.5095028
Bellpere 0.23991007 0.2612923 0.2612967 0.2715557 0.3876347 0.4673342 0.4697798
              CCA8
Achimill 0.6405579
Agrostol 0.7765521
Airaprae 0.4510074
Alopgeni 0.7341331
Anthodor 0.5096177
Bellpere 0.4700591
```

It seems that in the transition from the old `goodness.cca` code to the one that was `goodness2.cca` this functionality got lost. [Originally we had](https://github.com/vegandevs/vegan/blob/2084f4e485473e38648c0abc14307217eb4cbe47/R/goodness.cca.R#L55):

```r
    if (!missing(choices)) 
        vexp <- vexp[, choices, drop = FALSE]
```

but this is not in the newer (current) version for the code.

This is clearly a bug, but do we want to return the original `choices` functionality or update the documentation.

If we reinstate the functionality, it seems we need a better check that just not being `missing`; in the example in #189 there is only a single constrained axis so asking for `choices = 1:3` doesn't make sense.

**Comment by smikhaylov** [comment]
Referencing this issue and example in #189, any reason why you cannot have contributions to unconstrained axes? That is, beyond CCA `choices`.

**Comment by gavinsimpson** [comment]
@smikhaylov Maybe I wasn't thinking this through clearly enough... I suppose it makes no difference whether the particular linear combination is constrained or not when computing this, but the current code separates them into `CCA` and `CA` axes. In your case with `method = "CCA"`, there is only one column of goodness of fit stats and in that case we'd need to handle a user specification of `choices = 1:3` better than what was in the original code.

This is not to say that we couldn't `cbind` on unconstrained axes so that we had goodness stats for the selected axes, but this is easy for the user to do as well by calling `goodness` twice.

**Comment by smikhaylov** [comment]
I think either way would work fine. `method` argument could be more hardwired, it's not really reacting to `choices` specification right now.

**Comment by jarioksa** [comment]
Dropping `choices` looks accidental. Probably we should reinstate the functionality. It is easy to imagine cases where this usual: think about hundreds of unconstrained axes, or the desire to see how well a 2D plot represents each point.

There are numerous examples how this has been done in **vegan**. Mere `!missing(choices)` is not enough, but you need to check that `choices` do not exceed rank. In `summary.cca` and `stressplot` we first `cbind` components and then apply `choices` or rank (`k` in `stressplot`). This would call for a radical-ish re-design. In some other functions we remain within components (and always check for the existence of `choices` before applying them -- or fix this as a bug like in e804435ce earlier today).

**Comment by jarioksa** [comment]
I opened up branch [issue-#190](https://github.com/vegandevs/vegan/tree/issue-%23190) in vegandevs/vegan to put back `choices`. Please work further with that branch so that we avoid too many loose ends in the repository. Commit 4026ba47dd0 offers one solution to the issue. It seems there are many alternative ways of implementing `choices`. In normal usage they are all equal, but there are differences in corner cases:

* What should happen with `choices = 3:1`? Current commit reverses the axes and gives cumulation from 3 to 1. This sounds weird, but it was the user command.
* What should happen with `choices = 2:3`? Current commit will ignore axis 1 and give cumulation only for axes 2 and 3.
* What should happen with `choices = 2:3` and `addprevious = TRUE`? Current commit will add previous components but still ignore axis 1 of this component.
* What should happen with `choices = 1:2` and `summarize = TRUE`? Current commit will give the summary (total) only for chosen components.

**Comment by smikhaylov** [comment]
I think it makes sense. Probably just needs adjusting documentation now. The use of `model` argument is now required if you go beyond constrained dimensions. A couple example to illustrate (using data from #189).

```{r}
devtools::install_github("vegandevs/vegan", ref = "4026ba4")
library(vegan)
words <- read_csv("words.csv")
env <- read_csv("env.csv")
cca <- cca(words ~ Idealpoint, data = env)

goodness(cca) #contribution to inertia on CCA1
goodness(cca, choices = 1:3) #produces only contribution to inertia on CCA1
goodness(cca, model = c("CCA", "CA"), choices=1:3) #produces only contribution to inertia on CCA1

#so to go for unconstrained axes you need to specify `model`
goodness(cca, model =  "CA", choices=1:3)

#not specifying the `model` results in a warning message and null vector of results
goodness(cca, choices=2:3)
Warning message:
In sweep(CA, 1, tot, "/") :
  STATS is longer than the extent of 'dim(x)[MARGIN]'
```
 So I think it works fine, just documentation needs to be adjusted, particularly about the `model` argument for unconstrained `choices`.
