### ISSUE TITLE
Problems with simper function

### ISSUE THREAD

**Issue by bpantaferreira** [vegandevs/vegan#191]
hi guys, newbie here so don't bury me too fast please!

I'm trying to run simper in a community matrix, in which the last column stands for the treatment (actually, I'm trying to search for diferences between two groups that I believe are worth exploring after doing an NMDS).

So, treatment code is column "clust", data is "dados_fig_clust", and I'm getting this error:

Error in unique(as.character(group)) : object 'clust' not found

It's probably an obvious mistake, but I'm totally lost here. Can anyone help please?

btw  I've read the warning on SIMPER in the help file, but it's a mandatory test for my current task...

I'm just trying to find out what species (and how much) are "causing" the differences between the two clusters. The NMDS gave me a good answer, but my guys want numbers.

sorry, just to finish it

simper_fig=simper(dados_fig_clust, clust)
Error in unique(as.character(group)) : object 'clust' not found
simper_fig=simper(dados_fig_clust, "clust")
Error in combn(unique(as.character(group)), 2) : n < m
group 2 only has one place(station). group 1 has 7.

**Comment by bpantaferreira** [comment]
sorry, just to finish it

> simper_fig=simper(dados_fig_clust, clust)
Error in unique(as.character(group)) : object 'clust' not found
> simper_fig=simper(dados_fig_clust, "clust")
Error in combn(unique(as.character(group)), 2) : n < m

group 2 only has one place(station). group 1 has 7.

**Comment by gavinsimpson** [comment]
This is just a standard scoping issue. Consider the data frame `df`:

```r
df <- data.frame(A = 1:3, B = 2:4)
```

I can't refer to the variables (columns) `A` or `B` without reference to the data frame in which they reside:

```r
> A
Error: object 'A' not found
> B
Error: object 'B' not found
```

If I tell R where to look for the variables then everything is fine

```r
> df$A
[1] 1 2 3
```

It's not possible to know from the info you provide exactly what the call should be but you want something like

```r
simper_fig <- simper(dados_fig_clust, foo$clust)
```

Where `foo` is whatever data frame contains `clust`. If `clust` is a column of `dados_fig_clust`, then you probably don't want that and you should probably do

```r
clust <- dados_fig_clust$clust
```

and then delete or index out this column when calling `simper()`.

**Comment by bpantaferreira** [comment]
thank you so much for helping me with this, I know it's a simple doubt but well, I'm still learning, a whole lot of the R magic still escapes me.

Anyway, it worked as a charm. 

> cumulative contributions of most influential species:
> 
> $A_B
>     G_spinifer N_swammerdamei     M_fragilis     E_dollfusi 
>      0.3567940      0.5253951      0.6769372      0.7815749 


Just another question. I'm trying to export the results, but neither write.table or data.frame functions worked. Is there any way I can extract this data into a table or something?

> write.table(simper_fig, file="simper_fig.txt")
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""simper"" to a data.frame
> simper_table<-data.frame(simper_fig)
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""simper"" to a data.frame

I've tried other ways, but nothing...

> dat=summary(simper_fig)
> write.table(dat, file="simper_fig.txt")
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""summary.simper"" to a data.frame
> simper_table<-data.frame(dat)
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""summary.simper"" to a data.frame

then I came up with this, but didn't work.

as.data.frame(simper_fig)
Error in as.data.frame.default(simper_fig) : 
  cannot coerce class ""simper"" to a data.frame

I'm guessing there will be some kind of easy function for this, and I'm researching, but nothing came up. Thanks in advance and sorry for bothering with such basic questions, but I am a bit desperate.

**Comment by EDiLD** [comment]
simper has not a easy object structure and the data cannot be easily converted to a data.frame.
Nevertheless, you can extract the needed information from the summary object and save it to a file:

This prints a file for one contrast (SF vs BF):
```{r}
library(vegan)
data(dune)
data(dune.env)
(sim <- with(dune.env, simper(dune, Management)))


ssim <- summary(sim)
# show structure (= list of data.frames)
str(ssim)
# data.frame for SF_BF contrast
ssim[['SF_BF']]
# write to file
write.table(ssim[['SF_BF']], file = 'SF_BF.txt')
```

**Comment by bpantaferreira** [comment]
@gavinsimpson  @EDiLD thanks so much for the help! 

Now on to Bioenv.

**Comment by bpantaferreira** [comment]
@EDiLD  sorry for bothering again, but I can't find the p value for my analysis. Is there any command to try to retrieve it?

thanks in advance

**Comment by EDiLD** [comment]
p-values are overrated...

You could  do a permutation procedure, see the `permutation` argument.  It is intentionally set to 0 (=no permuations), as this method has not been tested extensively. As far as i know, this is only available in vegan. 
Please read carefully the documentation to simper. If in doubt check also the source code.
