### ISSUE TITLE
rrarefy, samples with or without replacement?

### ISSUE THREAD

**Issue by wfinsinger** [vegandevs/vegan#213]
Hi,

I just wanted to double-check this: does the function rrarefy( ) generate a randomly rarefefied community data frame of given sample size, by sampling WITH or WITHOUT replacement?

Many thanks for your help,

walt

**Comment by jarioksa** [comment]
WITHOUT

**Comment by gavinsimpson** [comment]
As can be seen [here](https://github.com/vegandevs/vegan/blob/master/R/rrarefy.R#L23), sampling is done **without** replacement.
