### ISSUE TITLE
Error in FUN(X[[i]], ...) :    only defined on a data frame with all numeric variables In addition: Warning message: In Ops.factor(left, right) : ‘<’ not meaningful for factors

### ISSUE THREAD

**Issue by ninadesianti** [vegandevs/vegan#214]
What does it mean? I tried to run metaMDS command:

> library(vegan)
> Loading required package: permute
> Loading required package: lattice
> This is vegan 2.4-1
> library(MASS)
> specnmds <- read.csv("specnmdstrans.csv", header=T, sep=",")
> ord <- metaMDS(specnmds, autotransform = FALSE)
> Error in FUN(X[[i]], ...) : 
>   only defined on a data frame with all numeric variables
> In addition: Warning message:
> ## In Ops.factor(left, right) : ‘<’ not meaningful for factors
> 
> My data consist of a matrix of 603 species (in columns) in 100 samples (in rows) with sample ID in the first column, the header is a list of short name of species, no space.

**Comment by BErfanian** [comment]
Dear nina,
you should exclude the column of sample ID from your data frame, simply delete it, before you load it.
Regards.

**Comment by jarioksa** [comment]
@BErfanian is probably correct (although we have no possibility of checking your data). See also [vegan FAQ](https://github.com/vegandevs/vegan/blob/master/vignettes/FAQ-vegan.Rmd#i-have-only-numeric-and-positive-data-but-vegan-still-complains).

**Comment by ninadesianti** [comment]
I removed the first column which contain a list of sample codes and it works! Thanks @BErfanian and @jarioksa !
