### ISSUE TITLE
Bug in species tolerances in tolerance.cca

### ISSUE THREAD

**Issue by gavinsimpson** [vegandevs/vegan#216]
The species tolerances in `tolerance.cca` are incorrect as the code is only indexing the second axis.

**Comment by gavinsimpson** [comment]
Commit 500a2e2 fixes the main problem here.

There is an outstanding issue though; the Canoco 5 user manual claims Canoco 5 uses N2 to debias the the species tolerance but not the sample heterogeneity, because it only computes these statistics using scores scaled to show response variable distances (basically our `scaling = 2` IIRC). This suggests that to match Canoco we need to either

* lock down the interface to not allow the user choosing other scalings or,
* we need to remove the `useN2` argument and turn it on/off as needed depending on the scaling types, or
* we note the issue in the Rd page and let users shoot themselves in the foot if they're not careful?

Thoughts @jarioksa?

I could ask Petr/Cajo for more detail on what Canoco does - I doubt the output from Canoco will be helpful in tracking this down as often bias correction is small and the outputs in v5 are rounded to 4dp.

**Comment by gavinsimpson** [comment]
I have now cherry-picked the relevant commits into the `cran-2.4`. We can wait to fix the the remaining issue if you want to get 2.4-2 out to CRAN.

**Comment by jarioksa** [comment]
Fine! I'll start wrapping up vegan 2.4-2 for the release. Do you want to write a NEWS entry for 2.4-2?

**Comment by gavinsimpson** [comment]
@jarioksa Done in bb8525a
