### ISSUE TITLE
Lambda^+ funnel plot

### ISSUE THREAD

**Issue by BErfanian** [vegandevs/vegan#220]
Hi,
Is there any way to implement a new option for [plot](https://github.com/vegandevs/vegan/blob/c7251ef076491e6f018cb6d9b6cb5b53199a605f/R/plot.taxondive.R) function in [taxondive](https://github.com/vegandevs/vegan/blob/c7251ef076491e6f018cb6d9b6cb5b53199a605f/R/taxondive.R) to draw Lambda^+ funnel (as fig.5. b in Clarke and Warwick, 2001)?
I try to change the plot code for myself, but it seems that it's necessary to change taxondive code to calculate expected values for Lambda^+, and i failed in that.
Thanks.

**Comment by jarioksa** [comment]
The `taxondive` function was last changed in 2007, and I need some reading to see how to implement new features. I hardly have time to this in 2016, and the field is open for anybody to implement expected Lambda^+.

**Comment by BErfanian** [comment]
Thanks, I'll wait for that.

**Comment by jarioksa** [comment]
I finally had a time to look at Clarke & Warwick (*MEPS* **216,** 265-278; 2001). I think that this method cannot be directly implemented in `taxondive`, but it can implemented an an `oecosimu` case. The current `plot` of the `taxondive` result is based on the analytic estimates of variance of *Delta+* (Clarke & Warwick, *JAE* **35,** 523-531; 1998), but no such analytic expression is provided for *Lambda+*. Graph 5.1 in Clarke & Warwick (2001) is based on simulation that we do not provide within `taxondive`. If I read it correctly, Clarke & Warwick (2001) define the confidence limits from subsamples with certain numbers of species. In **vegan** this can be achieved with `oecosimu`  null model `"r0"` that takes subsamples of the original number of species for each site. This allows pointwise comparison. 

Continuing from `example(taxondive)` which uses `dune` data and taxonomic distances in `taxdis`, we can issue

```R
library(vegan)
example(taxondive) # to get the data
par(ask = FALSE) # to draw graphics
## run the simulation and see its results
out <- oecosimu(decostand(dune, "pa"), taxondive, "r0", statistic="Lambda", dis=taxdis, 
     nsim=1000)
out
## plot
nsp <- specnumber(dune)
## need order by nsp to draw lines
i <- order(nsp)
with(out$oecosimu, plot(nsp, statistic, xlab="No. of Species", ylab="VarTD"))
## confidence limits still jagged with 1000 simulations
with(out$oecosimu, matlines(nsp[i], 
     t(apply(simulated[i,], 1, quantile, probs=c(0.025, 0.5, 0.975))), lty=1))
```
