### ISSUE TITLE
How to report adonis with three factors

### ISSUE THREAD

**Issue by naarkhoo** [vegandevs/vegan#229]
As adnois (permanova) is a sequential hypothesis testing method, and the ordering of factors in the formulation matter, I was curious how one should report the result. 

I am trying to answer across time whether factor A is more influential on microbioal variation or Factor B , therefore, I can look into the p-value and the R squared. 

`adonis(GPdist ~ week_experiment + A + B, df)`

Should I report p-value / R^2 for all 6 possible configuration of the factors ?

**Comment by jarioksa** [comment]
For `adonis` and sequential tests in general, the order of terms should be meaningful. If it is not meaningful, the tests are hardly meaningful.

Current **vegan** (in CRAN) also has `adonis2` function that can do marginal tests. Try that, if you need marginal statistics. However, R^2 are not meaningful for marginal tests and are not reported by `adonis2`.

**Comment by naarkhoo** [comment]
Since the question is sorting the effects (time, A, B) based on their impact on the output, I don't have any prior knowledge on the ordering - so I assume, your answer is yes, try 6 configuration.

Regarding adonis2, I would like to have some sort of a effect size, otherwise, I can't sort them only based on p-value.

**Comment by naarkhoo** [comment]
"_If it is not meaningful, the tests are hardly meaningful._" is the case, so I assume trying it in various orders, is the suggested approach

**Comment by jarioksa** [comment]
I do **not** recommend using all possible orders. Either you do marginal tests and accept the statistics it can deliver, or you have an *a priori* meaningful order.

**Comment by caifang** [comment]
Hello Naarkhoo,

 I am wondering how to do to get the sort of a effect size for your three factors, I have the same problem now.

**Comment by Jing-Y-oss** [comment]
> For `adonis` and sequential tests in general, the order of terms should be meaningful. If it is not meaningful, the tests are hardly meaningful.
> 
> Current **vegan** (in CRAN) also has `adonis2` function that can do marginal tests. Try that, if you need marginal statistics. However, R^2 are not meaningful for marginal tests and are not reported by `adonis2`.

what the meaning of  "R^2 are not meaningful for marginal tests"

**Comment by Jing-Y-oss** [comment]
> For `adonis` and sequential tests in general, the order of terms should be meaningful. If it is not meaningful, the tests are hardly meaningful.
> 
> Current **vegan** (in CRAN) also has `adonis2` function that can do marginal tests. Try that, if you need marginal statistics. However, R^2 are not meaningful for marginal tests and are not reported by `adonis2`.

what's the meaning of "R^2 are not meaningful for marginal tests"？
