### ISSUE TITLE
ANOSIM analysis

### ISSUE THREAD

**Issue by gomtaeng87** [vegandevs/vegan#232]
Hi,
I have a problem in running ANOSIM (analysis of similarity) especially in regards to grouping.
I used below code for ANOSIM.
```r
anosim(dat, grouping, permutations = 999, distance = "bray", strata = NULL,
    parallel = getOption("mc.cores"))
```
On the above anosim code, I managed to create dat part (dissimilarity index) using "dist" code.
However, I cannot run anosim with dat because I miss "grouping" part and I have no idea of how I can assign group information on my dat.

Could you please tell me how I can solve this grouping problem?
Thank you very much in advance for your kind help!

**Comment by jarioksa** [comment]
`grouping` must be a vector of classification. Its length must be equal to the number of observations (number of rows in data frame), and it gives the classification for each observation.
