### ISSUE TITLE
Procrustes/protest p-value

### ISSUE THREAD

**Issue by campenr** [vegandevs/vegan#236]
Hello

I couldn't find the information I wanted in the manual so I hope someone here can help.

I am performing multiple procrustes analyses using the `protest` function in vegan and want to adjust the p-values to account for the multiple testing. My question is, are the p-values output by protest the actual p-values, or are the prettified in some way? I ask because if they are not the actual p-values then it seems inappropriate to adjust them directly.

Cheers
Richard

**Comment by jarioksa** [comment]
They are permutation *p*-values. They are not "prettified" in any way, but as they are based on permutations,  they are "pretty". With default 999 permutations, the smallest possible *p*-value is 0.001 and the next possible is 0.002 (0 is not possible). If you want to get more resolution or less pretty values, you must increase the number of permutations.

**Comment by gavinsimpson** [comment]
That said, what is printed does go through a formatting step, which could alter *exactly* what gets *printed*. We have a `format.pval()` call in `print.protest()`, which is dependent on whatever you have set for `digits`: https://github.com/vegandevs/vegan/blob/master/R/print.protest.R#L11

If you want to grab the unadulterated *p* value, use `obj$signif` where `obj` is the object returned by `protest()`.

**Comment by campenr** [comment]
Thank you. I understood they are permutation p-values but something I read (can't remember where) gave me impression the values returned we're not the raw p-values. For my purposes it sounds like they are the same though.

Thanks!!
