### ISSUE TITLE
avgdist silently drops observations

### ISSUE THREAD

**Issue by jarioksa** [vegandevs/vegan#246]
Function `avgdist` will silently drop observations (rows) from the data. This can lead into mysterious mismatches with supplementary data sets. The minimum is to warn on dropping of data. The **vegan** standard is not to drop data, and the underlying `rrarefy` function does not drop observations. NB @Microbiology .

**Comment by Microbiology** [comment]
Thanks for making this @jarioksa. Sorry, I know we had talked about it before but it fell through the cracks. I'll be able to take care of this sometime in the next couple of days.

**Comment by jarioksa** [comment]
Closed with PR #251 (commit 2bcd09e6cdb6d10c).
