### ISSUE TITLE
Release plan for 2.5-0 and 2.4-4

### ISSUE THREAD

**Issue by jarioksa** [vegandevs/vegan#247]
I'm starting to clean up the current **vegan** master (2.5-0) branch for the release. This is a large change, in particular for constrained ordination and compiled code. The constrained ordination methods have been completely redesigned. Currently they fail in corner case, such as zero-rank components, and these must be fixed up. The domain of compiled code has been expanded, and now we use `.Call` interface extensively (permutation tests for constrained ordination which are not much faster, simulation of null models, even `decorana` and `designdist`). From this moment I'm less reluctant to accept any large changes, but I rather focus on cleaning up the current code base. 

Before the major 2.5-0 release, I intend to push minor 2.4-4 release that includes bug fixes from the master, and also fixes the warnings and notes we now get in the CRAN checks. If you thing some more changes should be merged to the 2.4-4 release, please speak out.

**Comment by jarioksa** [comment]
version 2.4-4 was released to **CRAN** on Aug 24, 2017 UTC. I'll start working with the 2.5-0 release.

**Comment by gavinsimpson** [comment]
I'm on vacation just now. Back on Monday. Will finish `ordicluster` then.

**Comment by jarioksa** [comment]
@gavinsimpson , there is a lot of boring work before the 2.5-0 release. The changes are so sweeping that extensive testing is needed for border cases. The `ordicluster` stuff is wanted for 2.5-0, but a lot of work needs be done before the 2.5-0 release.
