### ISSUE TITLE
Loading vegan leads to sessiong aborted

### ISSUE THREAD

**Issue by lker5lker5** [vegandevs/vegan#249]
Everytime I load the package, R stuio will be restarted because of the abored session. Don't know why, and how to fix it?

**Comment by jarioksa** [comment]
No idea. You don't provide much information to answer your question. I don't use **RStudio**, and it looks like the problem is there.

**Comment by gavinsimpson** [comment]
Also, make sure all packages have been installed with the version of R you
are using. You don't say what OS you are running R & RStudio on but recent
changes in R may mean packages containing compiled code need to be
reinstalled.

Try

```
update.packages(checkBuilt = TRUE, ask = FALSE)
```

Also make sure you aren't loading a workspace when you start R.

Finally, to check if this is an R or RStudio issue, start R on its own (not
via RStudio) and try to load vegan in that R session.

**Comment by lker5lker5** [comment]
Bang bang bang, thanks for your help. I've ran that update command, and I tried both R on its own and R studio, the package is now successfully loaded. btw, I am running on Win10. Guess the key point is reinstallation of some packages. So happy! Thanks again!

**Comment by jarioksa** [comment]
Fine!
