### ISSUE TITLE
AICc for fitspecaccum object

### ISSUE THREAD

**Issue by NivDeMalach** [vegandevs/vegan#250]
Hi,
I try to apply model selection approach for different models using the 'fitspecaccum' function.
When I apply AIC it works. but when I try AICc I get the following error message

_**Error in UseMethod("logLik") : 
  no applicable method for 'logLik' applied to an object of class "c('fitspecaccum', 'specaccum')"**_ 

Thanks,
Niv

**Comment by jarioksa** [comment]
When I try `AICc`, I get this message:

```r
> AICc(mods)
Error: could not find function "AICc"
```
So it looks like **R** does not have function `AICc` in **base** or **stats**. I guess `AICc` is in some add-on package, and nobody has written a method to access `fitspecaccum` results for that package. However, judging from your error message it could be sufficient to write a `logLik` method for `fitspecaccum`.

**Comment by jarioksa** [comment]
Please note that `fitspecaccum` are not nested which means that you cannot use `AIC` or `AICc` to select between them. People do so, but it is not correct.

**Comment by NivDeMalach** [comment]
Thanks a lot for your help,

Indeed AICc comes from the "MuMIn' package...
After adding this logLik function I get a new error message 'Error in nobs.default(object) : no 'nobs' method is available'. Do you have another suggestions?


P.S. The assertion that AICc cannot be used for non-nested models is **very controversial**( but common among R users since it was proposed by Ripley). I believe that most of the experts in the field would disagree (see example below). Are you aware of any other method for comparing nonlinear models that can be used for 'fitspecaccum' (BIC also doesn't work...)

https://sites.warnercnr.colostate.edu/anderson/wp-content/uploads/sites/26/2016/11/AIC-Myths-and-Misunderstandings.pdf

**Comment by jarioksa** [comment]
I assumed that mere `logLik.fitspecaccum` would not suffice. Obviously you also need  a `nobs` method:

```r
nobs.fitspecaccum <-
    function(object, ...)
{
    sapply(object$models, nobs, ...)
}

Once we get a list of all needed method functions, I'll add them to **vegan**.

**Comment by NivDeMalach** [comment]
Thanks again!
Now, I don't get an error message anymore but something else is wrong I get the value 
"numeric(0)"

**Comment by jarioksa** [comment]
It seems that we need the following functions:

```r
`logLik.fitspecaccum` <-
    function(object, ...)
{
    out <- sapply(object$models, logLik, ...)
    ## sapply() strips attributes: get'em back
    attr(out, "df") <- 1L + length(coef(object$models[[1]]))
    attr(out, "nobs") <- nobs(object$models[[1]])
    class(out) <- "logLik"
    out
}

`nobs.fitspecaccum` <-
    function(object, ...)
{
    sapply(object$models, nobs, ...)
}
```

**Comment by NivDeMalach** [comment]
It works! 

Thanks a lot

**Comment by jarioksa** [comment]
Fine! Now I can give an easier way of doing the same:

```r
## mod is a fitspecaccum result object
sapply(mod$models, AICc)
```

This does not need any new **vegan** functions. I didn't want to give that at once because I wanted someone to test that the new functions also work and are sufficient...

**Comment by jarioksa** [comment]
Closed with commit 4759e1ffa7ec04

**Comment by gavinsimpson** [comment]
@jarioksa 

> Please note that `fitspecaccum` models are not nested which means that you cannot use AIC or AICc to select between them. People do so, but it is not correct.

I hear both sides of this.

Reading Simon Wood's new 2nd Edition of Generalized Additive Models: an Introduction with R, [he claims](https://books.google.ca/books?id=JTkkDwAAQBAJ&lpg=PT326&dq=generalized%20additive%20models%20an%20introduction%20with%20R%20cult%20of%20AIC&pg=PT86#v=onepage&q=generalized%20additive%20models%20an%20introduction%20with%20R%20cult%20of%20AIC&f=false) that comparing models via AIC doesn't require the models to be nested, but if they are some terms in the approximation of the expected K-L divergence cancel.

**Comment by jarioksa** [comment]
It is just the same for me how you do if you are aware of what you do.
