### ISSUE TITLE
How are envfit P-values calculated?

### ISSUE THREAD

**Issue by KasperSkytte** [vegandevs/vegan#264]
Hi!
Thank you for a great package. I have a question about environmental variable fitting for ordination plots. How exactly are the p-values calculated? The documentation of the `envfit` function ([link](http://cc.oulu.fi/~jarioksa/softhelp/vegan/html/envfit.html)) only says: "_pvals: Empirical P-values for each variable_.". I tracked down the code that seem to do the calculation (below), but trying to figure it out from the raw code is probably a waste of time. Can you briefly explain how the P-values are calculated or estimated? 

Thanks in advance

**vegan::vectorfit() line 33-51**
```R
  ptest <- function(indx, ...) {
      take <- P[indx, , drop = FALSE]
      take <- .C("wcentre", x = as.double(take), as.double(w), 
        as.integer(nrow(take)), as.integer(ncol(take)), 
        PACKAGE = "vegan")$x
      dim(take) <- dim(P)
      Hperm <- qr.fitted(Q, take)
      diag(cor(Hperm, take))^2
    }
    permstore <- sapply(1:permutations, function(indx, ...) ptest(permat[indx, 
      ], ...))
    if (!is.matrix(permstore)) 
      permstore <- matrix(permstore, ncol = permutations)
    permstore <- sweep(permstore, 1, r - EPS, ">=")
    validn <- rowSums(is.finite(permstore))
    pvals <- (rowSums(permstore, na.rm = TRUE) + 1)/(validn + 
      1)
```
**and wcentre C-function**
 
```R
// c source: src/goffactor.c#L49-L67
void wcentre(double *x, double *w, int *nr, int *nc)
{
     int i, j, ij;
     double sw, swx;

     for (i = 0, sw = 0.0; i < (*nr); i++)
	  sw += w[i];

     for (j = 0; j < (*nc) ; j++) {
	  for (i = 0, swx = 0.0, ij = (*nr)*j; i < (*nr); i++, ij++) {
	       swx += w[i] * x[ij];
	  }
	  swx /= sw;
	  for (i = 0,  ij = (*nr)*j; i < (*nr); i++, ij++) {
	       x[ij] -= swx;
	       x[ij] *= sqrt(w[i]);
	  }
     }
}
```

**Comment by jarioksa** [comment]
You permute the data and recalculate the statistic in the permuted data. Then you order the statistics from permuted data and put the observed value of the statistic among them. The *P*-value is the proportional rank of the observed statistic among the statistics evaluated in permutations.

**Comment by KasperSkytte** [comment]
Okay. So essentially the probability that the observed is random? Thank you for your response.

**Comment by gavinsimpson** [comment]
@KasperSkytte If you aren't familiar with permutation tests, the vignette that comes with the **permute** package might help you get a clearer understanding of what is going on. It doesn't speak to the specific test statistic in `envfit` but it does describe permutation tests in general. **vegan** uses permute to generate the permutations.
