### ISSUE TITLE
Changing x-axis when using rarecurve

### ISSUE THREAD

**Issue by marijn1990** [vegandevs/vegan#265]
Hello everybody,

I have a short but simple question: when making rarefaction curves using rarecurve:

`rarecurve(x, step = 20, xlab = "Reads", ylab = "OTUs", label = FALSE)`

Is it possible to change the size of the x-axis? I currently get the normal rarefaction curves with an x-axis of with values of about 0 to 200,000 but I'd like to zoom in at 0-2,000, more or less. In this way, I can show what the effect would be of rarefaction at 100 and 1000 reads using `abline`.

Thank you for your help!

**Comment by psolymos** [comment]
How about `rarecurve(x, step = 20, xlab = "Reads", ylab = "OTUs", label = FALSE, xlim=c(0, 2000))`?

**Comment by marijn1990** [comment]
Strange - didn't work earlier but now does. I must have done something wrong Thank you very much...
