### ISSUE TITLE
goodness no longer implemented for capscale

### ISSUE THREAD

**Issue by RoelandKindt** [vegandevs/vegan#275]
error with goodness for a capscale object

**Comment by RoelandKindt** [comment]
Can see now from NEWS that this is no longer possible. Suggest therefore to update the documentation of the goodness function.

**Comment by jarioksa** [comment]
Thanks for the report. The documentation is now update in commit 4a434b7. 

Actually the functions could be implemented for `capscale`, but I was too lazy to do so. The comments of commit 5d7a83d37 tell how to do this:

>    disable goodness() for capscale: it is possible but not done now
    
> See stressplot.capscale for the model of implementing goodness for
    capscale. Basically we should run svd() on Fit and Xbars to get the
    column scores that can be used to reconstruct distances.

With modern **vegan** we need to use `ordiYbar()` for the task.

Pull requests are gladly accepted.
