### ISSUE TITLE
Error in diversity() : input data must be non-negative

### ISSUE THREAD

**Issue by Kayzinthan** [vegandevs/vegan#284]
I have a problem with the function diversity() with my data set. I got the error message "Error in diversity(Species) : input data must be non-negative" though my data set have no negative integer. Please help me with this and I attached my data file
[Sites_spp.xlsx](https://github.com/vegandevs/vegan/files/2101356/Sites_spp.xlsx)
 . Thank you very much for your help and welcome all suggestions!

**Comment by BErfanian** [comment]
Hi, 
transpose your data before loading it into vegan,
load your data with the "header=T" and "row.names=1" arguments. 
good luck

**Comment by Kayzinthan** [comment]
Thank you so much ....It works :)

**Comment by JunaidMikail** [comment]
Hey guys

can anyone help with error showing input data must be Non negative. However, I've tried to do all that is expected of e I'm still coming up with error

Thanks

**Comment by jarioksa** [comment]
Remove the variables with negative values. You have data with negative values because the computer says so, and you should never argue with your computer: you will lose.
