### ISSUE TITLE
decostand

### ISSUE THREAD

**Issue by mollyng** [vegandevs/vegan#290]
using vegan 2.5-2, I get an error that says object decostand not found.

**Comment by psolymos** [comment]
@mollyng can you give a bit more context or an MRE? `decostand` is an exported **vegan** function in version 2.5-2. If it were a NAMESPACE issue (which is not I am sure) you would get `Error: could not find function "decostand"` instead of `Error: object 'decostand' not found`.

**Comment by mollyng** [comment]
it says Error: object 'decostand' not found. ( i don't know how to do that fancy thing you just did)

**Comment by mollyng** [comment]
i was trying to define some variables. I have actually been struggling with CCA and predict, and would really appreciate help with CCA... which also gave me a similar error under vegan 2.5-2

> vegan<-cca(clim, anat) #(x,y)
Error in cca(clim, anat) : could not find function "cca"

**Comment by EDiLD** [comment]
Did you install (`install.packages("vegan") `)  and load (`library("vegan") `) vegan before running this line? Without seeing a Minimum Reproducible Example, I don't think that's an issue of vegan.

**Comment by jarioksa** [comment]
Probably not a vegan issue.
