### ISSUE TITLE
fisher.alpha when abundance and species richness are 0

### ISSUE THREAD

**Issue by alexology** [vegandevs/vegan#296]
Hi,

I have a question regarding the calculation of fisher alpha when abundance and number of species are 0 (probably a question more conceptual than practical). When I compute fisher alpha with the fisher.alpha function the result is 1:

```R
library(vegan)

# a data.frame of 3 columns with the first row filled with 0 and the second filled with 2. 
# The second row serves as control for my calculation (see below). 
# The third row is filled with 2202 that returns an alpha equal to 1.

ex <- as.data.frame( t( matrix( c( rep( 0 , 10 ), rep( 2 , 10 ), rep( 2202 , 10 ) ), ncol = 3) ) )
ex

# result for the first and third columns is 1
fisher.alpha(ex)

```

The problem is that the first and the third rows have exactly the same result despite the first row consisting of 0's only. Then I came across the book from Magurran (2004) “Ecological Diversity and its measurement”, where she propose to calculate alpha following:

S/N = (1 – x) / x*[ -ln(1 – x)]
alpha = N( 1 – x ) / x

where S is the number of species, N the number of individuals and x the log series distribution parameter.
I tried to calculate alpha according to Magurran 2004 and the results for the first columns is 0, while those for the second and the third columns are nearly the same of fisher.alpha results:

```R
# function for calculating fisher alpha according to Magurran et al. (2004)
fa.mag <- function(z){
  abu <- sum( z )
  ntaxa <- sum(z > 0)
  fn <- function( r , n , x )( abs( ( 1 - x )* n / x * ( -log( 1 - x ) ) - r ) )
  temp <- optimize( f = fn , interval = c( 0 , 1 ) , n = abu , r = ntaxa , tol = 0.0000001)[[1]]
  alpha <- abu * ( 1 - temp ) / temp
}

apply(ex, 1 , fa.mag)

```

Results are more understandable for me now, but I’m not sure if I interpreted the fisher alpha in the right way. The drawback for the Magurran et al. calculation is that when abundance become very high (2*10^8) x approaches 1 and alpha become greater than 1 again (probably is a problem of my bad coding). The behaviour of the 2 functions for large numbers is showed below:

```R
Seq = c(seq(from = 0, to = 9990, by = 10), seq(from = 10000, to = 10000000, by = 100000))
ex2 = as.data.frame(matrix(0, nrow = length(Seq), ncol = 10))
for(i in 1:length(Seq)){
  ex2[i,] = rep(Seq[i], 10)
}


veg.res <- fisher.alpha(ex2)
mag.res <- apply(ex2,1, fa.mag)

par(mfrow = c(1,2))
plot(veg.res, ylim = c(0,3), type = "l")
abline(h = 1, lty = 2, col = "red")
plot(mag.res, ylim = c(0,3), type = "l")
abline(h = 1, lty = 2, col = "red")
```

What the value of fisher alpha should be when both abundance and species richness are 0? This could happen when a user use a subset of a data.frame.

Thank you very much, regards.
Alex

```R
sessionInfo()

R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=it_IT.UTF-8       LC_NUMERIC=C               LC_TIME=it_IT.UTF-8       
 [4] LC_COLLATE=it_IT.UTF-8     LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=it_IT.UTF-8   
 [7] LC_PAPER=it_IT.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] vegan_2.4-5     lattice_0.20-35 permute_0.9-4  

loaded via a namespace (and not attached):
[1] MASS_7.3-50     compiler_3.4.4  Matrix_1.2-14   parallel_3.4.4  tools_3.4.4    
[6] mgcv_1.8-25     nlme_3.1-137    grid_3.4.4      cluster_2.0.7-1
```

**Comment by jarioksa** [comment]
I asked what should we do, but nobody answered since December 2018. No interest, no reason to keep this open.
