### ISSUE TITLE
choices  in plot.cca

### ISSUE THREAD

**Issue by pezhmansafdari** [vegandevs/vegan#297]
Hi,

I am trying to plot other RDAs than just 1 and 2 but, when I use the choices option, no matter which axes I choose, I will get the same results.  Would you please give me some advice about this? 
And, I also would like to know what percentage of the variance is explained by each RDA. In pcomp, we get that from the sdev data. I could not find similar data in the rda results.

All the bests,
Pezhman Safdari

**Comment by gavinsimpson** [comment]
I can't reproduce this with the CRAN release of *vegan*. You'll need to provide the code you are running, insure you are running the the most recent release of *vegan*, and possibly if the problem persists, an actual working example that we can run.

Here's a reproducible example that shows the plots are different:

```r
library('vegan')
data(dune)
data(dune.env)

ord <- rda(dune ~ ., data = dune.env)

layout(matrix(1:2, ncol = 2))
plot(ord, choices = c(1,2))
plot(ord, choices = c(2,3))
layout(1)
```

producing

![vegan-issue-297](https://user-images.githubusercontent.com/514696/49302029-914a5780-f48b-11e8-8da0-81d1c93b7c6a.png)

This is with:

```
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                                      
 version  R version 3.5.1 Patched (2018-11-17 r75624)
 os       Fedora 29 (Workstation Edition)            
 system   x86_64, linux-gnu                          
 ui       X11                                        
 language (EN)                                       
 collate  en_CA.UTF-8                                
 ctype    en_CA.UTF-8                                
 tz       America/Regina                             
 date     2018-11-30                                 

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version  date       lib source        
 assertthat    0.2.0    2017-04-11 [1] CRAN (R 3.5.1)
 backports     1.1.2    2017-12-13 [1] CRAN (R 3.5.1)
 base64enc     0.1-3    2015-07-28 [1] CRAN (R 3.5.1)
 callr         3.0.0    2018-08-24 [1] CRAN (R 3.5.1)
 cli           1.0.1    2018-09-25 [1] CRAN (R 3.5.1)
 cluster       2.0.7-1  2018-04-13 [1] CRAN (R 3.5.1)
 crayon        1.3.4    2017-09-16 [1] CRAN (R 3.5.1)
 desc          1.2.0    2018-05-01 [1] CRAN (R 3.5.1)
 devtools      2.0.1    2018-10-26 [1] CRAN (R 3.5.1)
 digest        0.6.18   2018-10-10 [1] CRAN (R 3.5.1)
 fs            1.2.6    2018-08-23 [1] CRAN (R 3.5.1)
 glue          1.3.0    2018-07-17 [1] CRAN (R 3.5.1)
 lattice     * 0.20-38  2018-11-04 [1] CRAN (R 3.5.1)
 magrittr      1.5      2014-11-22 [1] CRAN (R 3.5.1)
 MASS          7.3-51.1 2018-11-01 [1] CRAN (R 3.5.1)
 Matrix        1.2-15   2018-11-01 [1] CRAN (R 3.5.1)
 memoise       1.1.0    2017-04-21 [1] CRAN (R 3.5.1)
 mgcv          1.8-25   2018-10-28 [1] CRAN (R 3.5.1)
 nlme          3.1-137  2018-04-07 [1] CRAN (R 3.5.1)
 permute     * 0.9-4    2016-09-09 [1] CRAN (R 3.5.1)
 pkgbuild      1.0.2    2018-10-16 [1] CRAN (R 3.5.1)
 pkgload       1.0.2    2018-10-29 [1] CRAN (R 3.5.1)
 prettyunits   1.0.2    2015-07-13 [1] CRAN (R 3.5.1)
 processx      3.2.0    2018-08-16 [1] CRAN (R 3.5.1)
 ps            1.2.1    2018-11-06 [1] CRAN (R 3.5.1)
 R6            2.3.0    2018-10-04 [1] CRAN (R 3.5.1)
 Rcpp          1.0.0    2018-11-07 [1] CRAN (R 3.5.1)
 remotes       2.0.2    2018-10-30 [1] CRAN (R 3.5.1)
 rlang         0.3.0.1  2018-10-25 [1] CRAN (R 3.5.1)
 rprojroot     1.3-2    2018-01-03 [1] CRAN (R 3.5.1)
 sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.5.1)
 usethis       1.4.0    2018-08-14 [1] CRAN (R 3.5.1)
 vegan       * 2.5-3    2018-10-25 [1] CRAN (R 3.5.1)
 withr         2.1.2    2018-03-15 [1] CRAN (R 3.5.1)
```

**Comment by EDiLD** [comment]
See the FAQ 

https://cran.r-project.org/web/packages/vegan/vignettes/FAQ-vegan.html

for details on explained variance.

**Comment by pezhmansafdari** [comment]
Hi again!
I found the source of the problem. I have to put the "choices" option in all of the "with" lines as well. 
Thanks a lot,
Pezhman

**Comment by gavinsimpson** [comment]
Right; if you are building a plot up from lower-level function calls you need to pass all scores-rrlelated arguments, like `choices`, `scaling`, etc.

**Comment by jarioksa** [comment]
I have regarded this as an "issue" since 2002 when Dave Roberts and I had a long discussion about the issue. Ideally, functions like `points`, `text`, `ordi*` should know the basic settings in the previous graph so that you need not repeat things like `choices`, `scaling` etc. The **magrittr** pipes since 2.5-1 give one (but not complete) solution. An alternative is  that there is a vegan environment (`.LastVeganPlot`) that holds the specifis of the last plot. A better (in principle) is to have a vegan environmental variable that holds the plots specificis.

**Comment by gavinsimpson** [comment]
@jarioksa indeed; we discussed this some time back when you were investigating `%>%`. I can't recall if we thought about this at the time, or if it would involve too much of a change to **vegan** (I haven't gone back and looked), but when one calls `plot()` an object of class `ordiplot()` is returned, let's call that `foo`. Is there anything stopping us doing `points(foo, ....)` and having it just pull what is needed from `foo`?

And having now looked at this, it's what we already cater for this!

So, perhaps a more pertinent question is why don't we go back through examples and change them to show that paradigm

```r
oplt <- plot(ord, type = 'n', choices = 2:3, ....)
points(oplt, what = 'species')
text(oplt, what = 'sites')
```

? (that should be taken as pseudocode as I'm not sure the `points()` (well `scores()`) method is sophisticated enough to handle `what`/`display` as well as `plot.cca` and friends. Again, I haven't checked closely, but `scores.ordiplot` seems to only recognise as options for `what` the names of the list of scores stored in the ordiplot object.)

**Comment by jarioksa** [comment]
Yes, `plot`  only returns the scores requested in its call. If no explicit request is made, the underlying `scores`  method will decide what to take. For `rda`, `cca`  and like the `scores.cca`  will be used with default `display = c("sp","wa","cn")` and only these can be shown, unless we call `plot` which explicit `display` argument. Making `scores` return **all** possible result items, but only using some of these, could solve the chaining problem. Pull requests  are welcome.

The invisible `ordiplot`  object also works with different `ordi<addelement>` functions retaining scaling etc. So you can (and probably should) use
```r
oplt <- plot(ord, type = "n", choices=2:3, scaling="species", correlation=TRUE)
ordiellipse(oplt, ...)
```
so that you need not keep track with your graphics options.

Some of these issues and their limitations were already discussed in issue #257 (with added philosophical ramblings).
