### ISSUE TITLE
Decostand "frequency" 

### ISSUE THREAD

**Issue by invertdna** [vegandevs/vegan#304]
decostand provides the method "frequency" as an option for standardization, and I think the helpfile might be incorrect:  

"frequency: divide by margin maximum and multiply by the number of non-zero items, so that the average of non-zero entries is one (Oksanen 1983; default MARGIN = 2)."

But carrying out the operations as described does not yield a mean of one.  For example: 
```r
a <- sample(0:9, 100, replace = T)  #create some random data; note that it doesn't matter whether these are integers or decimals, etc. 
b <- a/max(a)     #divide by margin max
d <- b*sum(b!=0)   #multiply by number of non-zero items
mean(d[d!=0])   #take mean of non-zero items
```
yields an integer between about 45 and 55, depending on the sampling.  

By contrast, 
```r
f <- decostand(a, method = "frequency") 
mean(f[f!=0])
```
does have the intended effect of making the mean of non-zero numbers equal to zero.  

The code for decostand has the following:

```r
frequency = {
        if (missing(MARGIN)) MARGIN <- 2
        tmp <- pmax(k, apply(x, MARGIN, sum, na.rm = na.rm))
        fre <- apply(x > 0, MARGIN, sum, na.rm = na.rm)
        tmp <- fre/tmp
        x <- sweep(x, MARGIN, tmp, "*")
    }
```

Which essentially divides the number of non-zero entries by the vector SUM, and then multiplies the vector by that dividend.  

In sum, I think the helpfile wrongly describes the operation performed.

**Comment by jarioksa** [comment]
Corrected in commit 6617fca2af1bdd528232e778a9a7eef58ed5f558. Thanks.
