### ISSUE TITLE
Shannon Weiner, Diversity, and Unknown NA's

### ISSUE THREAD

**Issue by R-Tard** [vegandevs/vegan#313]
I cant figure out why im getting NA. I am brand new to R, I am trying to help a friend out with some work and I cant figure this out to save my life. Hopefully my error is painfully obvious and I wont take up too much of your time. 
Here is the code I would like to run 
```r
library(vegan)
Data<-read.csv("makesmesad.csv", header = TRUE)
attach(makesmesad)
names(makesmesad)
diversity(makesmesad,index = "shannon")
```
This is the output I am given 
```r
 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[31] NA NA NA NA NA NA NA NA NA NA NA
```

I was looking around at some other posts, none of the suggestions corrected my issue.  Could anyone point me in the right direction ?

Cheers~~
[makesmesad - Copy.xlsx](https://github.com/vegandevs/vegan/files/3124672/makesmesad.-.Copy.xlsx)

**Comment by BErfanian** [comment]
Add zeros in the empty cells of your data. Remove the environmental factors in your data.

**Comment by R-Tard** [comment]
Wow, thanks for the prompt reply. I replaced null cells with 0's but I am still getting the same behavior :/

Here is an updated excel file....did I miss something ?
[makesmesader.xlsx](https://github.com/vegandevs/vegan/files/3124691/makesmesader.xlsx)

**Comment by BErfanian** [comment]
It is better for your data to look like this attached file:

[makesmesad.zip](https://github.com/vegandevs/vegan/files/3124697/makesmesad.zip)

**Comment by R-Tard** [comment]
Ok I can work with that :) 

I tried your corrected file and it gave me an error for the input data needing to be numeric.

I checked the class and it looks like it's type is character ?

My friend and I tried changing it with .....
makesmesad1<-as.numeric(makesmesad1)
matrix(data)
asend

It didn't fly :/    
I feel as if I am struggling with the basics of this system 😔

**Comment by BErfanian** [comment]
Try to read the instruction, and check each example that is presented for every function in the vegan or other packages. 
This works: 
Data<-read.csv(file.choose(),row.names = 1, header = TRUE) # browse to find your data
div_shan=diversity(Data,index = "shannon") #run the analysis
div-shan #it shows the results

good luck.

**Comment by jarioksa** [comment]
This seems to work:
```r
x <- read.csv("makesmesader.csv", head=TRUE, row.names=1) # after transforming xlsx to csv
x[is.na(x)] <- 0 # two NA (empty cells) still in bignose.shark (column 4): replace with 0
library(vegan)
diversity(x[,-1]) # must remove the catch total from calculation
```
