### ISSUE TITLE
Question about by="terms"/by="margin" argument in adonis2

### ISSUE THREAD

**Issue by ktmbiome** [vegandevs/vegan#314]
HI,

I'm using adonis2, and am testing a multivariable model. First, looking at the univariate model, my main effect is not significant. When I add potential confounders to this model and use `by="margin"`, my main effect is still not significant. However, when I switch to `by="terms"`, my main effect (the first variable in the model) becomes significant.

I was previously under the impression that in using `by="terms"`, the variables were tested for significance from first to last. Therefore, I would have thought that my first variable should have remained consistent, both in effect size (which it is) and p-value (which it isn't). Is there something missing in my understanding?

Any thoughts would be greatly appreciated!

Best,
--Katie

**Comment by jarioksa** [comment]
The residuals and the *F* value will change. Usually this does not change *P*-values so much, but this can happen.

**Comment by ktmbiome** [comment]
Do you have a sense for when it could happen? Is it typically from having co-linear variables? Just curious, since this is the first time that I've seen something like this.

**Comment by jarioksa** [comment]
It is also the first time that I saw such drastic changes. Small differences are normal. The analysis would need looking at the data and the models.
