### ISSUE TITLE
bug in plot.envfit

### ISSUE THREAD

**Issue by XavierTB** [vegandevs/vegan#315]
Hi, I came across a possible bug in vegan 2.5-4 with `plot.envfit`
When I plot an envfit object with the `at=c(x,y)` argument, the vectors' origin is displaced by x,y, but the labels are displaced by 2x,2Y, as in the following instance:

 
![image](https://user-images.githubusercontent.com/51135419/58507800-d1686980-8192-11e9-80fd-20f3e6168212.png)

generated with:
```r
plot(env)
plot(env,at=c(1,-2))
```

I had a look at plot.envfit, I think the offending line is: 
```r
 vtext <- sweep(vtext, 2, at, "+")
```
because `vtext` is already at the new location from the previous `ordiArrowtextXY` command

Best

**Comment by jarioksa** [comment]
Thanks for reporting this. It is now fixed following your suggestion (plus some fine tuning).
