### ISSUE TITLE
Add support for adonis in RsquareAdj

### ISSUE THREAD

**Issue by apcamargo** [vegandevs/vegan#316]
Currently, the `adonis` function only provides non-adjusted R2 values. To get adjusted R2, the user must provide the R2, degrees of freedom and number of observations manually. It would be really useful if `RsquareAdj` could take in an `adonis` object.

**Comment by jarioksa** [comment]
How would you define such adjusted _R_<sup>2</sup> values for terms?

**Comment by jarioksa** [comment]
I elaborate my comment: In general, you cannot the adjusted _R_<sup>2</sup> for terms in `adonis` by entering _R_<sup>2</sup> and other data into `RsquareAdj`. If you have done so, stop doing it! `RsquareAdj` works only when the term can be regarded as the only term in the model. In default `adonis` (and the only choice with old `adonis`) was sequential test (`by = "terms"`). Here `RsquareAdj` works for the first (and *only* the first term). Other reported _R_<sup>2</sup> values give the *improvement* after previous terms, or differences between two _R_<sup>2</sup> values, and `RsquareAdj` gives wrong results for these.

If you need to get adjusted _R_<sup>2</sup> values, you should use `varpart` function that finds these differences. Current version of `varpart` can also handle dissimilarities. You only need to know which rows to read from the `varpart` result. The following example uses current development version (vegan 2.6.0) of `adonis` – in the release version (2.5.x) `adonis2` is the corresponding function.

```r
library(vegan)
data(dune, dune.env)
dis <- vegdist(dune) # Bray-Curtis
adonis(dis ~ Management + Moisture + Use, dune.env, by = "term") # only choice in old adonis
##           Df SumOfSqs      R2      F Pr(>F)    
##Management  3   1.4686 0.34161 3.5630  0.001 ***
##Moisture    3   1.1516 0.26788 2.7940  0.003 ** 
##Use         2   0.1675 0.03896 0.6096  0.800    
##Residual   11   1.5113 0.35155                  
##Total      19   4.2990 1.00000  

## corresponding  varpart,
## displaying only lines that match the adonis output above
varpart(dis, ~ Management, ~ Moisture, ~ Use, data=dune.env)
## Partition table:
##                       Df R.square Adj.R.square Testable
## [a+d+f+g] = X1         3  0.34161      0.21816     TRUE               
## [b+e] = X2 | X1        3               0.21109     TRUE
## [c] = X3 | X1+X2       2              -0.03647     TRUE
```

Only the first term could be found with `RsquareAdj`.

The adjusted _R_<sup>2</sup> values also depend on the model you test. Here similar tables for marginal tests:
```r
### adonis:
adonis(formula = dis ~ Management + Moisture + Use, data = dune.env, by = "margin")
           Df SumOfSqs      R2      F Pr(>F)  
Management  3   0.5790 0.13469 1.4048  0.179  
Moisture    3   0.9434 0.21944 2.2888  0.012 *
Use         2   0.1675 0.03896 0.6096  0.822  
Residual   11   1.5113 0.35155                
Total      19   4.2990 1.00000
### varpart table:              
Individual fractions                                   
[a] = X1 | X2+X3       3               0.05267     TRUE
[b] = X2 | X1+X3       3               0.16769     TRUE
[c] = X3 | X1+X2       2              -0.03647     TRUE
```

**Comment by apcamargo** [comment]
Thank you for the explanation, @jarioksa . Indeed, I've been calculating adjusted R2 for a single term, so I think there are no problems with it.

```r
bray_16s <- vegdist(t(asvtab_16s))
adonis_16s <- adonis(formula = t(asvtab_16s) ~ Plant, data = metadata)
adonis_16s

Call:
adonis(formula = t(asvtab_16s) ~ Plant, data = metadata) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

          Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Plant      1     3.195  3.1951  8.6312 0.09523  0.001 ***
Residuals 82    30.355  0.3702         0.90477           
Total     83    33.550                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

get_adjusted_r2 <- function(adonis_object) {
  n_observations <- ncol(adonis_object$coef.sites)
  d_freedom <- adonis_object$aov.tab$Df[1]
  r2 <- adonis_object$aov.tab$R2[1]
  adjusted_r2 <- RsquareAdj(r2, n_observations, d_freedom)
  adjusted_r2
}

get_adjusted_r2(adonis_16s)

0.084201077474151
```

In any case, I was checking what you just said to me (that the reported R2 of the additional terms are just the increments over the R2 of the first term).

```
bray_16s <- vegdist(t(asvtab_16s))
adonis_16s <- adonis(formula = t(asvtab_16s) ~ Region + Plant, data = metadata, by = "terms")
adonis_16s

Call:
adonis(formula = t(asvtab_16s) ~ Region + Plant, data = metadata,      by = "terms") 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

          Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Region     1     4.862  4.8622  15.449 0.14492  0.001 ***
Plant      1     3.195  3.1951  10.152 0.09523  0.001 ***
Residuals 81    25.493  0.3147         0.75984           
Total     83    33.550                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

###

bray_16s <- vegdist(t(asvtab_16s))
adonis_16s <- adonis(formula = t(asvtab_16s) ~ Plant, data = metadata, by = "terms")
adonis_16s

Call:
adonis(formula = t(asvtab_16s) ~ Plant, data = metadata, by = "terms") 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

          Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Plant      1     3.195  3.1951  8.6312 0.09523  0.001 ***
Residuals 82    30.355  0.3702         0.90477           
Total     83    33.550                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

In this case the R2 of the `Plant` term is the same whether it was the first or second term. Shouldn't it be smaller in the case where it is the second term?

**Comment by jarioksa** [comment]
It seems that `Plant` is virtually uncorrelated with `Region`: Its sum of square is 3.1951 in both cases. If variables are uncorrelated, they can be entered in any order.
