### ISSUE TITLE
vegdist for beta diversity and permutation analysis

### ISSUE THREAD

**Issue by yogeshgupt** [vegandevs/vegan#320]
Hi,

I am trying to use vegan bioconducter package for beta diversity and permutation analysis for amplicon data but it is giving distance according to ASV instead of sample names, please help me with it.Is it also possible to give phyloseq object to vegan command instead of txt files?

```
> werra_sp <- read.table("convent.fert.root.count.txt",header=T,sep='\t',check.names=F,row.names=1)
    > werra_env <- read.table("werra.env.txt",header=T,sep='\t',check.names=F,row.names=1)
    > str(werra_sp)
    'data.frame':   1327 obs. of  18 variables:

     $ Root-19.S46.L001: int  44 0 52 16 13 0 0 32 7 0 ...

     $ Root-22.S56.L001: int  0 0 114 0 0 0 0 40 7 0 ...

     $ Root-24.S66.L001: int  43 0 484 24 0 6 0 17 0 0 ...

     $ Root-25.S76.L001: int  22 0 82 19 0 0 0 31 0 22 ...

     $ Root-26.S6.L001 : int  0 14 0 0 0 0 0 10 0 0 ...


    > str(werra_env)

    'data.frame':   18 obs. of  2 variables:

     $ Treatment: Factor w/ 1 level "convent.fert.": 1 1 1 1 1 1 1 1 1 1 ...

     $ Region   : Factor w/ 2 levels "Mymensingh","Rajshahi": 1 1 1 1 1 1 1 1 1 2

    > dist_werra <- vegdist(werra_sp^0.25, method= 'bray')
    > dis

    > dist_werra
                                     270d52396ceaab2f1506f5a6c6100c10
    d644684b08ae9b136307d9d2ce8975c0                       0.89217116
    aed34f36d535976c247278bec289fd12                       0.36933629
    731354d360c13253dfe2ad2d2b0cd971                       0.41469186
    030329dbd6777daa2f0a75400b60b583                       0.59543568
```

**Comment by gavinsimpson** [comment]
FYI *vegan* is an R package and nothing whatsoever to do with Bioconductor although some Bioconductor packages build upon or make use of *vegan*'s functionality.

I am finding that it is typical for data such as these amplicon data to be transposed relative to the usual expectation that samples are in the rows and variables or features are in the columns. If you look closely at the output from `str(werra_sp)` you'll see that it reports 18 **variables** yet for `str(werra_env)` we have 18 **observations** (`obs.`). Vegan expects that the samples be the rows hence I think you just need to transpose `werra_sp`:

    werra_sp <- as.data.frame(t(werra_sp))

> Is it also possible to give phyloseq object to vegan command instead of txt files?

No; it is not possible to pass *vegan* a `phyloseq` object, though there may be functions in other R or Bioconductor packages that do one of the following:

1. wrap *vegan* functionality such that they read the *phyloseq* object, convert it to an appropriate format and then call the relevant *vegan* function, or
2. provide a function to convert *phyloseq* objects into matrices or data frames that *vegan* can ingest natively.
