### ISSUE TITLE
CRAN Warning

### ISSUE THREAD

**Issue by jarioksa** [vegandevs/vegan#322]
I got the following message from CRAN:

> Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_vegan.html>.

> Please correct before 2019-08-19 to safely retain your package on CRAN.

The issue itself is really insignificant:

```
checking Rd cross-references ... WARNING
Missing link or links in documentation object 'oecosimu.Rd':
  ‘[labdsv]{rndtaxa}’

See section 'Cross-references' in the 'Writing R Extensions' manual.
```

However, this opens up a window for other fixes (such as PR #300 for @gavinsimpson )

**Comment by gavinsimpson** [comment]
I'll work on #300 

I heard tell that the submission queue was going to be closed until later in August. If true, we might want to clarify those closure dates and then decide whether to get this done ASAP and in before the close or wait until it reopens, but if that is post the 18th we might want to let CRAN know our intentions.

**Comment by jarioksa** [comment]
The CRAN issue is really insignificant and I already fixed that. In addition, there are a couple of bug fixes and one clean-up of user interface, and I could pack up vegan_2.5-6 very soon. NEWS of the changes is the only piece that is needed. 

I also noticed that CRAN incoming queue will closed on Friday August 8, but I could quite well submit the package by Thursday if we don't want more time for any other reason.

**Comment by jarioksa** [comment]
@gavinsimpson : I added NEWS about changes. vegan_2.5-6 would be ready for CRAN as it stands now. The only question is, do we want it be something more than it stands now.

**Comment by gavinsimpson** [comment]
@jarioksa the PR in #300 would be easy to merge but the bigger issue is adding the same functionality or ideas for some other related functions as you mention in #300. I won't have time before the 8th to deal with the larger issue, so if you want to push this fix to CRAN to avoid issues, I'm cool with that. I'll be able to work on the bigger set of functions at the weekend.

**Comment by jarioksa** [comment]
@gavinsimpson I uploaded 2.5-6 to CRAN. It includes the CRAN fix, two bug fixes and one tidying of printed results. The #300 should be fixed some day, but it is not really crucial for this release.

The CRAN incoming queue closes "tomorrow" (I assume UTC+2). Let's see if they can have this before that deadline. I won't tag this version before it's accepted.

**Comment by jarioksa** [comment]
Submission was rejected: http://www.worldagroforestry.org/resources/databases/tree-diversity-analysis gave 404 in `man/renyi.Rd`.

**Comment by jarioksa** [comment]
I got  a new message with a new deadline of 2019-09-03 (in the weird date format used in **R**). I have fixed the problem of the previous submission and added one new bug fix (Hill scaling is open-ended at top). I am preparing for a submission on Friday, August 30 (UTC+3) if there are no objections.

**Comment by jarioksa** [comment]
I tried again today, and submitted **vegan** after further editing. All changes are janitorial and mainly concern web addresses. These sunk the last submission, and new cases appeared in Win-Builder checks. It seems that CRAN is getting increasingly picky against insecure (`http://`) links and requests secure ones (`https://`). I went through all these and also checked that the web addresses were current and worked. Some web pages seemed to be unreliable: they change frequently and have no re-direction. Instead of chasing the current state of flux, I removed links to these. I also removed references to R-Forge (where we should nuke **vegan**), and also links to my `oulu.fi` web page which is due to disappear any day. This also means that there are no references to `vegantutor.pdf`: I don't know yet what to with it and where I could have it for distribution.

**Comment by jarioksa** [comment]
Release 2.5-6 was accepted today. Unfortunately this breaks **dispRity**: fixing issue `na.rm=FALSE` bug in `vegdist` (see issue #319) breaks one function in **dispRity** which had assumed the old buggy behaviour of passing `NA` to the C code.
