### ISSUE TITLE
Adonis Ordinal Variables

### ISSUE THREAD

**Issue by nearinj** [vegandevs/vegan#324]
Hello Devs,

I currently looking at using the adonis function to evaluate the relationship between a few variables of interest and a distance matrix. What I am currently trying to figure out is whether or not Adonis has a special way of dealing with ordinal variables.

I'm currently working with a variable that measures the number of days per week that the user ate a specific food item. I would like to use this as an ordinal variable (0 -7 days per week) as I get very different results when treating it as a factor or as a numeric (in respect to both p-val and r2 val). If you have any suggestions that would be awesome!

Thanks, Jacob Nearing

**Comment by jarioksa** [comment]
**R** handles ordinal _explanatory_ (_independent_) variables as ordered factors, and **vegan** uses the standard **R** way. However, `adonis` only gives the gross effects of explanatory variables, and these are the same for ordered and unordered factors. You would get the same results as you now get when treating your variables as factors.

**Comment by nearinj** [comment]
Hi Jari,

Thanks for clearing that up! I have been tackling issues were you get widely different results when treating things as factors vs. continuous variables and so I wanted to see if there was a best of dealing with this. 

Thanks, Jacob Nearing
