### ISSUE TITLE
Joint hypothesis test for PERMANOVA using adonis

### ISSUE THREAD

**Issue by deborahyqw** [vegandevs/vegan#326]
Hi,

Thank you for making this great package! One thing I've been struggling for a long time is doing a joint hypothesis test for PERMANOVA using adonis. 

For example for:
adonis(dune ~ Management*A1, data=dune.env, permutations=99) 
Is there a way to get a joint test for "Management + Management : A1"?

This test is useful in my research in microbiome, because first, it could act as a screening tool to find microbiota that may have significant main or interaction effect, and second, it may detect overall effects of the microbiota when tests that without the interaction would otherwise overlook the effects. 

I hope this test could be enabled for adonis (please correct me if there is already such a test in adonis). Thank you!

**Comment by jarioksa** [comment]
In **vegan** 2.5-x you can request overall test with `adonis2` using argument `by=NULL`. In current development version (2.6-0) `adonis` will do the same. Then it is only defining the formula:
```r
## vegan 2.5-6 - in vegan 2.6-0, use adonis() instead of adonis2()
> adonis2(dune ~ Management + Management:A1, dune.env)
Permutation test for adonis under reduced model
Terms added sequentially (first to last)
Permutation: free
Number of permutations: 999

adonis2(formula = dune ~ Management + Management:A1, data = dune.env)
              Df SumOfSqs      R2      F Pr(>F)    
Management     3   1.4686 0.34161 3.2629  0.001 ***
Management:A1  4   1.0301 0.23960 1.7164  0.054 .  
Residual      12   1.8004 0.41878                  
Total         19   4.2990 1.00000                  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> adonis2(dune ~ Management + Management:A1, dune.env, by=NULL)
Permutation test for adonis under reduced model
Permutation: free
Number of permutations: 999

adonis2(formula = dune ~ Management + Management:A1, data = dune.env, by = NULL)
         Df SumOfSqs      R2      F Pr(>F)    
Model     7   2.4987 0.58122 2.3792  0.001 ***
Residual 12   1.8004 0.41878                  
Total    19   4.2990 1.00000                  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```
Was this your question?

**Comment by deborahyqw** [comment]
Hi Jari,

Thank you so much for your reply! The problem is that my model contains several covariates. Sorry that I didn't make it clear in my question.

In the case of the following model, how to get the results for "Management + Management : A1" specifically?

adonis2(formula = dune ~ Management + Management : A1 + A1 + Moisture + Manure, data = dune.env)

Thank you!

**Comment by jarioksa** [comment]
You cannot have such structured models in `adonis2`, but you can use partial dbRDA for such a model. You partial out the terms that you do not want to analyse:
```r
mod <- dbrda(dune ~ Management + Management:A1 + Condition(A1 + Moisture + Manure),
     data = dune.env, distance = "bray")
anova(mod)
```

**Comment by deborahyqw** [comment]
Thank you so much!
