### ISSUE TITLE
contrast settings in PERMANOVA

### ISSUE THREAD

**Issue by HenrikEckermann** [vegandevs/vegan#327]
If I change the option `contr.ordered` or `contr.unordered` between `"contr.sum"` and `"contr.treatment"` using the adonis function, I get exactly the same results. This should be impossible if I use more than one factor. I tried it in different ways (including setting contrasts before the analysis manually vs not, using adonis2 and more. The results should be different depending on whether I use dummy contrasts (standard in R) or the `contr.sum` option. I guess I am overlooking something but if someone could confirm that this is an issue or point out what I am overlooking that would be great.

Here is a reproducible example using the dietswap dataset in the microbiome package:

```{r}
# load libraries and data
library(microbiome)
library(tidyverse)
data(dietswap)
pseq <- dietswap

metad <- meta(pseq)

# the variables of interest are factors:
class(metad$nationality)
class(metad$bmi_group)

library(vegan)
# different options lead to same results:
pm1 <- adonis(t(otus) ~ nationality + bmi_group, 
             contr.unordered = "contr.treatment",
             method = "bray", 
             permutations = 999,
             data = metad)

pm1$aov.tab

pm2 <- adonis(t(otus) ~ nationality + bmi_group, 
             contr.unordered = "contr.sum",
             method = "bray", 
             permutations = 999,
             data = metad)

pm2$aov.tab
```

**Comment by jarioksa** [comment]
The contrasts influence the _coefficients_, but they do not influence the _overall effect_  of the term. The anova table only gives the overall effects. To see the coefficients, you should look at `pm1$coef` (for species) and `pm1$coef.sites` (the species scores can be accessed also with `coef(pm1)`).
