### ISSUE TITLE
How to extract Average Distance to Median from betadisper object.

### ISSUE THREAD

**Issue by abalter** [vegandevs/vegan#331]
My understanding is that as far as assessing homoskedasticity (equal variance), the key result is average distance to median. These should be very close among the groups.

Is there a way to extract those values directly from the `betadisper` output object? I tried looking at `names(betadisper)`, `scores(betadisper)`, and `summary(betadisper)`, but none of them give access to the average distance to median.

The documentation gives no hints.

**Comment by jarioksa** [comment]
The output prints the average distances by groups. Is this the thing that you wanted? 

The manual tells that the result object returns the distances to the centroid:

> distances: numeric; the Euclidean distances in principal coordinate
          space between the samples and their respective group
          centroid.

If you want to recalculate the average, you can use (building from the example in manual):
```r
     data(varespec)
     
     ## Bray-Curtis distances between samples
     dis <- vegdist(varespec)
     
     ## First 16 sites grazed, remaining 8 sites ungrazed
     groups <- factor(c(rep(1,16), rep(2,8)), labels = c("grazed","ungrazed"))
     
     ## Calculate multivariate dispersions
     mod <- betadisper(dis, groups)
     ### Calculate groupwise mean distance to the centroid:
     with(mod, tapply(distances, groups, "mean"))
     ### the overall mean
     with(mod, mean(distances))
```
Is this what you asked for, or do you want something else?

**Comment by gavinsimpson** [comment]
> The manual tells that the result object returns the distances to the centroid:

I should probably edit that to indicate that it is distance to centroid *or median*...

**Comment by gavinsimpson** [comment]
> If you want to recalculate the average, you can use (building from the example in manual)

It would be pretty trivial to add this to the returned object. I'll take a look.

**Comment by gavinsimpson** [comment]
@abalter: although Jari has already shown how to get the information you want from the object returned by `betadisper()`, the development/github version of *vegan* will now return these group-wise average distances to centres as component `$group.distances` (See #333 and #334). If you want to try this out, you'll need to install that version of *vegan* from the github sources.
