### ISSUE TITLE
Add mean distance to centroid/median for each group in betadisper

### ISSUE THREAD

**Issue by gavinsimpson** [vegandevs/vegan#333]
The thread in #331 shows how to do this but this could easily be added to `betadisper()` and reported in the output.

`print.betadisper` already computes this (https://github.com/vegandevs/vegan/blob/be754d0e09bab59b3e00110f057c67896f9207ea/R/print.betadisper.R#L20) so it would make sense to compute this once in the object and then just prettify that rather than recompute it each time the object is printed.

**Comment by jarioksa** [comment]
@gavinsimpson : this is also the canonical way. The official party line is that `print` does no calculation, but just shows the result.

**Comment by gavinsimpson** [comment]
@jarioksa Yeah; I don't know why I did it this way. Anyway, easy to fix now.
