### ISSUE TITLE
installing vegan on linux error

### ISSUE THREAD

**Issue by parksnrec1** [vegandevs/vegan#340]
When I try to install the vegan package in Rstudio I get this:
> install.packages("~/Downloads/vegan_2.5-6.tar.gz", repos = NULL, type = "source")
Installing package into ‘/home/parks/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
ERROR: this R is version 3.2.3, package 'vegan' requires R >= 3.4.0
* removing ‘/home/parks/R/x86_64-pc-linux-gnu-library/3.2/vegan’
Warning in install.packages :
  installation of package ‘/home/parks/Downloads/vegan_2.5-6.tar.gz’ had non-zero exit status

I am using the latest version of R of linux, does this mean it is not possible to use the vegan package  with my OS? Is there a work around?

**Comment by gavinsimpson** [comment]
You aren't using the latest version of R; whatever OS you are on is providing you with a *very* out dated version of R.

Options are:

* see if your OS has a newer version/release out
* see if there is a newer version of R for your OS version
* download the sources for the current version of R and compile R yourself

To use vegan you'll need at least R 3.4.0, but preferably you'd be using 3.6.3, which is the released version at the time of writing.
