### ISSUE TITLE
typo in vegdist help: formula for euclidean?

### ISSUE THREAD

**Issue by JochenFruend** [vegandevs/vegan#342]
Hi, I think there are parentheses missing in help(vegdist):

euclidean d[jk] = sqrt(sum(x[ij]-x[ik])^2)
should be 
euclidean d[jk] = sqrt(sum((x[ij]-x[ik])^2))

Looks like the sum function has precedence over the ^2 function.

**Comment by gavinsimpson** [comment]
Thanks @JochenFruend Fixed now.
