### ISSUE TITLE
Design must be balanced if permuting 'strata!, how to use the "how" for unbalanced data?

### ISSUE THREAD

**Issue by BErfanian** [vegandevs/vegan#346]
Hi, 
I have a set of control and treated plots which had been sampled during years. I run the PRC function in the vegan package and want to perform a permutation test to check whether control vs treated plots significantly differ during years. As my data is unbalanced, I can not use strata function. my data looks like:

```
library(vegan)
year=as.factor(c(rep(1995,8),rep(1999,8),rep(2001,8),rep(2013,4),rep(1995,4),
       rep(1999,4),rep(2001,4),rep(2013,4)))
treatment=as.factor(c(rep("control",28),rep("treated",16)))
Although the folowing code is runing, but it lacked treatment!, So it is not right:
h1 <- how(within = Within(type = "series", mirror = F),
          blocks = year, nperm = 999
)
```

Thanks in advanced.

**Comment by gavinsimpson** [comment]
I have provided a response to your question on [StackOverflow](https://stackoverflow.com/a/60243307/429846); please follow-up there.
