### ISSUE TITLE
Error in plot.radfit.frame(x) : object 'gh' not found

### ISSUE THREAD

**Issue by sara-r50** [vegandevs/vegan#356]
I am an undergraduate student who is really new to coding and to using R. I am getting this error when I try to plot my radfit.frame object: 
"Error in plot.radfit.frame(x) : object 'gh' not found"

I am using the exact same code that had worked great in the past and had produced a panel of graphs fitting models to my data. I can plot the graphs individually by using "x$y" but it just refuses to make them into a panel. 

I do not have an object named "gh".

I think the problem started happening when I updated R to version 3.6.3 and vegan to version 2.5-6.

Thank you in advance.

**Comment by gavinsimpson** [comment]
@sara-r50 You'll need to provide a reproducible example (feel free to email me the data offline if you can't reproduce this without your data)

**Comment by jarioksa** [comment]
@sara-r50 There is no `gh` in **vegan** code, and we really do need a reproducible example. However, you could start by showing the _command_ that triggered the error (now we only see the error message). After getting the error, write `traceback()` and copy-paste its output here. It will show the line of code that actually gave the error.

**Comment by sara-r50** [comment]
Thank you for your responses!
Sorry for bothering you. I just cleared my environment and now it's working.

**Comment by gavinsimpson** [comment]
Thanks for the update @sara-r50
