### ISSUE TITLE
Function rarefy: Rdocumentation

### ISSUE THREAD

**Issue by JuliaHen** [vegandevs/vegan#357]
There might be a little mistake in the description of details for rrarefy and drarefy:

Function rrarefy generates one randomly rarefied community data frame or vector of given sample size. The sample can be a vector giving the sample sizes for each row. If the sample size **is equal to or smaller** than the observed number of individuals, the non-rarefied community will be returned.

Function drarefy returns probabilities that species occur in a rarefied community of size sample. The sample can be a vector giving the sample sizes for each row. If the sample **is equal to or smaller** than the observed number of individuals, all observed species will have sampling probability 1.

Shouldn't it be: ...is equal to or bigger...?

**Comment by jarioksa** [comment]
Thanks! Fixed now.
