### ISSUE TITLE
dispweight with non-integers

### ISSUE THREAD

**Issue by ailich** [vegandevs/vegan#360]
dispweight crashes when the community matrix has non-integer values. A community matrix could be non-integer values if counts are being converted to densities to compare sites of different sizes. 

`Error in nullmodel(comm[groups == lev, ], nullmodel) :   non-integer values not allowed`

**Comment by jarioksa** [comment]
`dispweight` does not crash, but it detects a user error and exits gracefully with an informative message to the user.

You can use `dispweight`  with non-integer data, but then you have to define a `nullmodel` that can handle non-integer data. The default `nullmodel = "c0_ind"` only handles integers. The help page asks you to consult `?commsim` for null models. This page also lists null models that can be used with non-integer data.

**Comment by ailich** [comment]
Ok thank you. My bad, "crash" was not the correct term there. Would `null_model="c0_samp"` perhaps be a valid null model to accomplish the task as it seems to operate similarly the the `"c0_ind"` method from Clarke et al. (2006) but can handle non-integers?
