### ISSUE TITLE
missing values are not allowed in rda analysis?

### ISSUE THREAD

**Issue by YunZhang0708** [vegandevs/vegan#363]
The version of vegan is 2.5-6. I am hoping to use rda to run my analysis, but I do have missing values,  when I use rda to run my analysis, vare.rda<-rda(dataspe~.,dataenv), the following  error appeared:
Error in na.fail.default(list(WT = c(1.399021502, 1.404850814, 1.38921926,  : 
  missing values in object
I wonder if there is any way to make data with NA available for RDA or vegdist analysis?

**Comment by jarioksa** [comment]
You should set the `na.action` argument to accept missing values. The default is `na.action = na.fail`, but you can set `na.action = na.omit` or `na.action = na.exclude`. As usual, this can be found by reading the help: try `?rda`.
