### ISSUE TITLE
Unable to install package under linux mint 19

### ISSUE THREAD

**Issue by RolfTMeles** [vegandevs/vegan#365]
I tried several methods. First I thought I had an outdated R-base version but I updated to 4.0.1 now. The dependencies are installed without any problem. It is easily done using R Studio but using the shell it also works. I can also verify that I have permute and lattice installed.

When I try to install vegan using the shell I get the following output:
```
> install.packages("vegan")
Installing package into ‘/home/rolf/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/vegan_2.5-6.tar.gz'
Content type 'application/x-gzip' length 2039486 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

* installing *source* package ‘vegan’ ...
** package ‘vegan’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-ec3D3l/r-base-4.0.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c data2hill.c -o data2hill.o
gfortran -fno-optimize-sibling-calls  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-ec3D3l/r-base-4.0.1=. -fstack-protector-strong  -c decorana.f -o decorana.o
/bin/bash: gfortran: komando ne trovita
/usr/lib/R/etc/Makeconf:190: recipe for target 'decorana.o' failed
make: *** [decorana.o] Error 127
ERROR: compilation failed for package ‘vegan’
* removing ‘/home/rolf/R/x86_64-pc-linux-gnu-library/4.0/vegan’

The downloaded source packages are in
	‘/tmp/RtmpNYbtZt/downloaded_packages’
Warning message:
In install.packages("vegan") :
  installation of package ‘vegan’ had non-zero exit status
```

**Comment by jarioksa** [comment]
The error message seems to be:

```
/bin/bash: gfortran: komando ne trovita
```

which (I assume) translates to `gfortran: command not found`. You do not have FORTRAN compiler, but you should install `gfortran`.

**Comment by RolfTMeles** [comment]
Is it a package? using `>install.packages("gfortran")` it says `package ‘gfortran’ is not available (for R version 4.0.1)`

**Comment by RolfTMeles** [comment]
Thank you! That kind of helped. I think I am getting there. Now I seem to need -llapack and -lblas...

**Comment by jarioksa** [comment]
No, it is not a package, but it is a compiler and a part of your operating system. You seem to have some a Linux, and there you can install the needed fortran using something like `apt-get` if you are Debian-based. Your OS may also provided a OS packages that contain all tools you need to compile **R** packages from the source. For instance, in Debian-based systems these are in `r-base-dev` that you can install with `apt-get install r-base r-base-dev` from the command line. However, I do not know Mint Linux: consult its documentation. This is not an **R** issue, but an issue of your Linux installation.

**Comment by jarioksa** [comment]
Here a link to instructions in Debian-based systems:

https://cran.r-project.org/bin/linux/debian/#general-information

**Comment by RolfTMeles** [comment]
Thank you so much for your help! Problem seems to be, that  Mint is mostly based on Ubuntu but some things only work like it was debian but still different. 
I see now that it was a Linux problem rather than R.

The solutions were:
a) to install gfortran
b) to install r-base-dev

It all works now, Thank you so much!
