### ISSUE TITLE
Issues with formulas in adonis

### ISSUE THREAD

**Issue by mgoggans** [vegandevs/vegan#368]
Hello,

I have an experiment with a repeated measures design. I would like to use PERMANOVA to test the entire model - the vignette says adonis can handle a formula notation, but I am having problems.

Repeated measures ANOVA is denoted as such:
dependent.variable ~ between.factor * within.factor + Error(id.of.repeat / within.factor)

When I try to run this, I get "Error: cannot find function "Error" "

This "error" notation in the formula is standard for base R linear models. I don't know why it won't work. Is adonis just not made to function with this type of linear model?

**Comment by jarioksa** [comment]
`Error` is not a part of `formula` documentation. It has been implemented as a special function in `aov()` (try `?Error` which takes you to `aov`), but will give an error, for instance, in `lm` where it is not implemented. It is neither implemented in `adonis` of **vegan**.

**Comment by mgoggans** [comment]
@jarioksa  Thank you for the thorough answer, very much appreciated!
