### ISSUE TITLE
shepard plot

### ISSUE THREAD

**Issue by jrfrun** [vegandevs/vegan#370]
I have what should be a simple response to my question but I am having problems with it.

I am creating a shepard plot (stressplot) having created a nonmetric distance or dissimilarity indicator via metaMDS

The plot is created successfully.  But I have to needs that I cannot find how to do them because it denies me
1.  I need to find a way to not insert the r square annotation in the graph,  
2. I need to change the axis labels to something I choose and not have it provide a default label

any help is welcomed

**Comment by jarioksa** [comment]
`stressplot` is a an old support function that was not intended for publication use and you really cannot configure its axis labels or annotation. However, you can catch the data it uses and reconstruct the graph you want to have (this is hinted to in the documentation which says in chapter *Value*:  "`stressplot` returns invisibly an object with items for original dissimilarities, ordination distances and fitted values." 
```r
library(vegan)
data(dune)
mod <- metaMDS(dune, trace=0)
pl <- stressplot(mod) # catch data in pl
str(pl) # see what you got
#List of 3
# $ x : num [1:190] 0.467 0.448 0.524 0.639 0.636 ...
# $ y : num [1:190] 0.455 0.808 0.75 0.665 0.881 ...
# $ yf: num [1:190] 0.497 0.497 0.669 0.883 0.883 ...
## x are observed dissim, y are ordination dists and yf are the values for fitted line
with(pl, plot(x, y, xlab="", ylab="", pch="+")) # set here plot characters
o <- with(pl, order(x, y)) # values are in data order: for line must be ordered by x, break ties by y
with(pl, lines(x[o], yf[o], type="S", col=2, lwd=2)) # similar type S stepline as default
```

I hope this helps.

**Comment by jrfrun** [comment]
thank you very much for the quick response and yes, it does help
