### ISSUE TITLE
betadisper throws an error when all distances are zero

### ISSUE THREAD

**Issue by FVFaleiro** [vegandevs/vegan#372]
Dear all, 
the betadisper crash when all values from the distance matrix is equal to zero. 
I did not find where is the error, but I think the function could return zero in this case as do not have dispersion in the data (see code below).

**Reproducible example**
```
x <- data.frame(sp1 = rep(1, 10), sp2 =  rep(2, 10), sp3 = rep(3, 10), sp4 = rep(4, 10))
g <- as.factor(c(rep("a", 5), rep("b", 5)))
d <- dist(x)
betadisper(d, g)
# Error in dimnames(x) <- dn : 
#  length of 'dimnames' [2] not equal to array extent
```
**Possible solution**
```
if (length(unique(d)) == 1 & unique(d) == 0)  {
  centroids <- rep(0, length(unique(group)))
  group.distances <- rep(0, length(unique(group)))
}
```

**Comment by jarioksa** [comment]
There are several other functions that also throw an error. I have now made minimal fixes to `betadisper`, `capscale`, `isomap`, `pcnm`, `wcmdscale` and also `scores.default`. All these had exactly the same problem: trying to set names to dimensions that did not exist. Now these no longer throw an error, but return these results as zero or NULL. However, in most cases you cannot do anything with these results, but you will probably get unrelated errors if you want, say, plot the results. Actually, I think that throwing an error was a legitimate thing to do: it was an error to use all-zero distances. 

In one case there really is a crash situation: `monoMDS` (and hence `metaMDS`) fail if all your dissimilarities are zero. Then the function just hangs in compiled code, and you cannot stop the function, but you have to kill **R**. I haven't fixed this yet, but I'll do it soon.

**Comment by jarioksa** [comment]
I have now fixed all issue that I found in branch 0-dist. I haven't merged this yet: please have a look this ( @gavinsimpson). My fix is minimal, and if you want to have more extensive fixes, you can work on your own branch or work on that 0-dist branch before merging it to master.

**Comment by jarioksa** [comment]
Fixed with commit listed above plus more.
