### ISSUE TITLE
Reshuffling of data produces completely different adonis results

### ISSUE THREAD

**Issue by liisaveerus** [vegandevs/vegan#381]
Dear vegan masterminds,

I hope you are well and healthy!

I have a question about reshuffling of meta data and why does that lead to completely different adonis2() results. I am attaching an example of the dune data set. 

<img width="447" alt="adonis" src="https://user-images.githubusercontent.com/52078155/94843175-fe7ef900-0424-11eb-96e6-d3c89965d87b.PNG">

The only difference between the data sets is that the rows in the second one have been reshuffled.

I am asking because I have a similar issue with my own data set. Dependent on the order of rows, I get completely different results. I set.seed(1234) every time, I have increased the permutations to 100,000, I play around with the strata... The only thing that explains the difference is the reshuffled rows. 

Your help would be much appreciated! Thank you!

**Comment by psolymos** [comment]
@liisaveerus Can you share how the `dune.env.shuffled` object was created? Have you shuffled the `dune` object the same way? If I reshuffle both, I get (almost) identical results:

```R
> adonis(dune ~ Management*A1, data = dune.env, permutations=1000)

Call:
adonis(formula = dune ~ Management * A1, data = dune.env, permutations = 1000) 

Permutation: free
Number of permutations: 1000

Terms added sequentially (first to last)

              Df SumsOfSqs MeanSqs F.Model      R2   Pr(>F)   
Management     3    1.4686 0.48953  3.2629 0.34161 0.001998 **
A1             1    0.4409 0.44089  2.9387 0.10256 0.025974 * 
Management:A1  3    0.5892 0.19639  1.3090 0.13705 0.228771   
Residuals     12    1.8004 0.15003         0.41878            
Total         19    4.2990                 1.00000            
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> adonis(dune[s,] ~ Management*A1, data = dune.env[s,], permutations=1000)

Call:
adonis(formula = dune[s, ] ~ Management * A1, data = dune.env[s, ], permutations = 1000) 

Permutation: free
Number of permutations: 1000

Terms added sequentially (first to last)

              Df SumsOfSqs MeanSqs F.Model      R2   Pr(>F)    
Management     3    1.4686 0.48953  3.2629 0.34161 0.000999 ***
A1             1    0.4409 0.44089  2.9387 0.10256 0.021978 *  
Management:A1  3    0.5892 0.19639  1.3090 0.13705 0.210789    
Residuals     12    1.8004 0.15003         0.41878             
Total         19    4.2990                 1.00000             
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

**Comment by liisaveerus** [comment]
![Code](https://user-images.githubusercontent.com/52078155/94854601-d64bc600-0435-11eb-9435-444fbc824342.png)
![Data](https://user-images.githubusercontent.com/52078155/94854603-d6e45c80-0435-11eb-9f8f-b7c2f1fe9340.png)

With my own data set, I noticed that the change emerged when I had re-ordered rows in my meta data .csv file that I manage in Excel. I then swapped the order back in the .csv file and got the OG results. 

I have made sure that I do not make mistakes in Excel. I have even tested this find with small subsets to confirm my sightings.

For clarification, my own data set is a phyloseq object (microbiota data) to which I attach the meta data each time that it has been altered (sometimes we need to add new information). Then, based on that, UniFrac distances are calculated (these remain unaltered by the order of the rows, I have checked) and adonis2() is run. 

I have detected this issue across many of my data sets---the order of rows in the meta data matters.

**Comment by jarioksa** [comment]
Please tell me what do you expect? You use randomised explanatory variables and get a random result. I would expect that (and actually `adonis` expects that: the permutation test is based on permutation  or "shuffling" of data!). What is surprising here? If you shuffle your explanatory variables, the *P*-values should have a uniform distribution between (0,1) (you call them "metadata", but they are not any obscure "metadata", but variables that you use to explain dependent data, and if they are shuffled, they are random).

**Comment by liisaveerus** [comment]
Dear Jari, Thank you for your prompt reply. I fully expect (and have seen this across my data sets) the values to vary. But not the significance patterns. E.g. dependent on the row order, completely different significant factors emerge. This makes me wonder how to tackle this issue. Do you have a suggestion?

**Comment by gavinsimpson** [comment]
If you *only* shuffled the `dune.env` data set, then you broke the relationships between the response `dune` and the environment. Indeed, this is the very basis for the permutation test used in `adonis()` etc to test the estimated effects of the environmental covariates.

There is no attempt in *vegan* to match up separate datasets on the basis of their row names; it is the user's responsibility insure that row 1 in the response corresponds to row 1 in the env data, and for all rows.

It's not clear from anything you've written here that you didn't just randomise the environmental data `dune.env`. If that's all you did then this is user error on your part. As @psolymos showed, if you do shuffle both data frames in the same way, the results are the same and therefore the results are not dependent upon the ordering of the data.

**Comment by jarioksa** [comment]
There is a question to tackle if the results change radically if you change the row order identically **both** in the dependent and independent variables: `k <- sample(nrow(y)); adonis(y[k,] ~ ..., data = x[k,])`. However, if you change the ordering only in one matrix (`adonis(y ~ ..., x[k,])`, like you seem to do in your example) then you should expect different and **random** results. If your results are random, then you should expect random *P*-values that are uniform in 0...1. This means, they are *P* < 0.05 with probability *P* = 0.05. In other words, some "significant factors emerge" at probability 0.05.

**Comment by jarioksa** [comment]
I'll close this: reshuffling of data **should** produce completely different results because reshuffle data are completely different.
