### ISSUE TITLE
unused argument (index = "shannon")

### ISSUE THREAD

**Issue by ilariamelcore** [vegandevs/vegan#388]
Dear all,
I am trying to calculate some indices with Vegan. At the beginning, when I had only "Vegan" package installed, it worked. After installed other packages like: 
install.packages("devtools")
library (devtools)
devtools ::install_github("gavinsimpson/ggvegan")
library(ggvegan)
library (diverse)

when I run my code: diversity (shrubs_J, index="shannon"), it gives me this error:
Error in diversity(shrubs_J, index = "shannon") : 
  unused argument (index = "shannon").

Can someone help me??
Thank you

**Comment by gavinsimpson** [comment]
The **diverse** package likely contains a function called `diversity` also. As this was loaded after **vegan** it *masks* the function in **vegan**, which is to say that the one in **diverse** is found first on the search path.

To call the **vegan** version, you need to fully qualify the function with the package namespace, as in

```r
vegan::diversity(shrubs_J, index = "shannon")
```
