### ISSUE TITLE
Error in vegan::diversity(x, index = "shannon") :    input data must be numeric

### ISSUE THREAD

**Issue by ilariamelcore** [vegandevs/vegan#389]
Hi all,
I am using Vegan to calculate indeces, like shannon, from my shrubs values. I am using a transpose csv file and these are the scripts I used:
habitat <- read.csv("Habitat.csv", sep = ";")
#select the shrubs columns
dataset <- habitat
shrubs <- dataset[c(6:26), c(2:85)]
#shannon index for transect J
shrubs_J <- dataset[c(6:26), c(2:8)]

vegan::diversity(shrubs_J, index = "shannon")

Then I got this error: Error in vegan::diversity(shrubs_J, index = "shannon") :   input data must be numeric.
And when I look at my values, they look like characters.
[Habitat.xlsx](https://github.com/vegandevs/vegan/files/5814440/Habitat.xlsx)

Can someone help me??
Thanks

**Comment by EDiLD** [comment]
> And when I look at my values, they look like characters.
Well, as the error message suggests this might be the problem.
Looking at your data, you might want to transpose it. 
This is not a `vegan` issue and can be closed.

**Comment by ilariamelcore** [comment]
OK,
I closed it.
Thanks for answering
