### ISSUE TITLE
building vegan on macOS with R-devel

### ISSUE THREAD

**Issue by FelixErnst** [vegandevs/vegan#397]
Hi,

I noticed a peculiar issue on a GitHub action, which errors on macOS with R-devel:

```
* installing *source* package ‘mia’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/runner/work/_temp/Library/vegan/libs/vegan.so':
  dlopen(/Users/runner/work/_temp/Library/vegan/libs/vegan.so, 6): Symbol not found: __gfortran_os_error_at
  Referenced from: /Users/runner/work/_temp/Library/vegan/libs/vegan.so
  Expected in: /usr/local/gfortran/lib/libgfortran.5.dylib
 in /Users/runner/work/_temp/Library/vegan/libs/vegan.so
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
```

I checked, which tests CRAN is running on R-devel, but it doesn't include macOS https://cran.rstudio.com/web/checks/check_results_vegan.html

So I guess this is a heads up, for the next R release, which might run into problems on macOS. Would you have time to check/fix this error?

Thanks in advance.

**Comment by jarioksa** [comment]
I use macOS myself, and have noticed no problems. However, the error message hints to problems in your Fortran tools: check that you have Fortran, and that  your Fortran versions have not changed, and the Fortran versions match between your vegan build and R build, and perhaps re-build vegan with R-devel.

**Comment by FelixErnst** [comment]
I of course forgot to post a link the GHA output: https://github.com/FelixErnst/mia/runs/1874578240

Since this a GitHub action running R-devel and R-release on CRAN doesn't have a problem, I assume that there are breaking changes with R-devel only.

Can you post your sessioninfo?

```
─ Session info ───────────────────────────────────────────────────────────────────────────────────
 setting  value                                             
 version  R Under development (unstable) (2021-02-07 r79964)
 os       macOS Catalina 10.15.7                            
 system   x86_64, darwin17.0                                
 ui       X11                                               
 language (EN)                                              
 collate  en_US.UTF-8                                       
 ctype    en_US.UTF-8                                       
 tz       UTC                                               
 date     2021-02-10          
```

**Comment by jarioksa** [comment]
I'm busy with preparing another package for the CRAN release, and I won't  have time to play with building R-devel for a week or so. However, there is nothing that indicates there is a problem in **vegan**. Rather, the messages you got indicate problems in your build and test environment, and you should fix those. I suggest you try by yourself (i.e., not in your automated environment, but just get your **mia** and test it by hand, also installing its dependencies in a non-automated system. It seems to me that either your automatic build system fails to download and build some dependencies, or uses binaries built with mixed incompatible versions of Fortran. If you do your test by hand, you will see.

Although there is no macOS entry for package tests with R-devel on macOS, such tests are run, and if they fail, there will be a header of "Additional Issues" with a link to the failing tests. In particular, now Brian Ripley runs these tests with bleeding edge R-devel in his Apple Silicom (M1). If **vegan** fails in any of these, he will certainly contact me and ask me to fix the problems. He has done so with another package, that I had to fix. He also maintains a list of packages that fail with R-devel + Apple Silicon M1 + macOS Big Sur. It is explained in this [R-SIG-Mac post](https://stat.ethz.ch/pipermail/r-sig-mac/2021-January/013870.html):

> - Binary packages are planned but the vast majority of packages install 
from source.  I currently have 240 CRAN check failures with 35 failing 
to install and 98 others requiring those (or BioC ones).  If you are 
interested in a particular package, 
https://www.stats.ox.ac.uk/pub/bdr/M1mac/ has recent logs for those 
failing directly, listed as 'additional issues' on their CRAN check pages.

**vegan** does not appear among these problem cases.

**Comment by jarioksa** [comment]
I'm busy with preparing another package for the CRAN release, and I won't  have time to play with building R-devel for a week or so. However, there is nothing that indicates there is a problem in **vegan**. Rather, the messages you got indicate problems in your build and test environment, and you should fix those. I suggest you try by yourself (i.e., not in your automated environment, but just get your **mia** and test it by hand, also installing its dependencies in a non-automated system. It seems to me that either your automatic build system fails to download and build some dependencies, or uses binaries built with mixed incompatible versions of Fortran. If you do your test by hand, you will see.

Although there is no macOS entry for package tests with R-devel on macOS, such tests are run, and if they fail, there will be a header of "Additional Issues" with a link to the failing tests. In particular, now Brian Ripley runs these tests with bleeding edge R-devel in his Apple Silicom (M1). If **vegan** fails in any of these, he will certainly contact me and ask me to fix the problems. He has done so with another package, that I had to fix. He also maintains a list of packages that fail with R-devel + Apple Silicon M1 + macOS Big Sur. It is explained in this [R-SIG-Mac post](https://stat.ethz.ch/pipermail/r-sig-mac/2021-January/013870.html):

> - Binary packages are planned but the vast majority of packages install 
from source.  I currently have 240 CRAN check failures with 35 failing 
to install and 98 others requiring those (or BioC ones).  If you are 
interested in a particular package, 
https://www.stats.ox.ac.uk/pub/bdr/M1mac/ has recent logs for those 
failing directly, listed as 'additional issues' on their CRAN check pages.

**Comment by FelixErnst** [comment]
I investigated this a bit further. The binary on CRAN for version 2.5.7 is apparently not compatible with R-devel. Rebuilding during the GHA solved the problem.
