### ISSUE TITLE
Change label names and type of numbers on x-axis for rarecurve()

### ISSUE THREAD

**Issue by mr2raccoon** [vegandevs/vegan#407]
Hey,

I drew a "rarecurve" from my "phyloseq-object".
1. How can I change the name of the labels for each curve ?
2. How can I change the numbers on x-axis to not show scientific numbers (4e+05) but "normal" numbers.
 I tried this ` scale_x_continuous(labels=function(n){format(n, scientific = FALSE)})` but it does not work. 
I tried different ideas from this post (https://stackoverflow.com/questions/11610377/how-do-i-change-the-formatting-of-numbers-on-an-axis-with-ggplot) but nothing works.

My code: `col <- c("darkred", "forestgreen")
NotFancy <- function(l) {
  l <- format(l, scientific = FALSE)
  parse(text=l)
}
rare_nano <- rarecurve(t(otu_table(physeqnano)), label=TRUE, col=col, xlab="Probenumfang", ylab="Artenanzahl") + scale_x_continuous(labels=NotFancy)
rare_nano + geom_text(title("Rarefactioncurve Nanopore")) `

**Comment by jarioksa** [comment]
You also asked this in [StackOverflow](https://stackoverflow.com/questions/66970719/), and I answered this question there. Let's keep this discussion only in one channel, and since you started in StackOverflow, let's that be the channel.
