### ISSUE TITLE
rda Error in qr.fitted(Q, Y) : 'qr' and 'y' must have the same number of rows

### ISSUE THREAD

**Issue by slambrechts** [vegandevs/vegan#411]
Hi,

When running 

`rda(formula = CSS ~ Bedrock + dem + pH_dest + TOC + N.NH4 + N_NO3 + P_PO4 + TN_perc + TP_perc + conductivity, data = metadata98, scale = T)`

I keep getting:

> Error in qr.fitted(Q, Y) : 'qr' and 'y' must have the same number of rows

I checked:

```
> dim(CSS)
[1] 21250    98
> dim(metadata98)
[1] 98 37
```

And there are no negative, NA or infinite values in both the community data matrix or in the metadata variables that are used in the formula.

also I tried with both a data frame version of the community data and a matrix version

Am I missing something else here?

**Comment by jarioksa** [comment]
The error message says that `'qr' and 'y' must have the same number of rows`. Indeed, 21250 is not equal to 98.

**Comment by slambrechts** [comment]
ok yes, that was indeed the problem, thank you!
