### ISSUE TITLE
What does ordiellipse plot as default if no kind or conf terms are given?

### ISSUE THREAD

**Issue by Ziggsblitz** [vegandevs/vegan#414]
My colleague and I were trying to figure this out and we found that the kind defaults to "sd" but couldn't tell what sort of confidence interval is used if none is provided.

**Comment by jarioksa** [comment]
None. Confidence levels are only used if they are given. So it defaults to draw sd ellipses. The documentation may be obscure, but it tries to say this:
> conf: Confidence limit for ellipses, e.g. 0.95. If given, the
          corresponding ‘sd’ or ‘se’ is multiplied with the
          corresponding value found from the Chi-squared distribution
          with 2df.
The key phrase is "if given...".
