### ISSUE TITLE
dbRDA (capscale) sites are missing

### ISSUE THREAD

**Issue by rigtm** [vegandevs/vegan#415]
Hi everyone, 

I'm trying to analyze my fish abundance / water quality data with dbRDA. I've been following several guides online, but I'm currently stuck at this stage, where my sites (7 in total) are not showing up and each observation was shown instead.

![image](https://user-images.githubusercontent.com/82358479/116967110-2ea4b800-ace4-11eb-829b-65ea1169cb83.png)

I've been trying to group the observation points into groups (my sites) but have not succeeded yet. Any tips how to do this? Thanks!

**Comment by rigtm** [comment]
I ended up adding a new column manually for the sites on summary(dbRDA)$sites and got it to work that way. Hours of frustration but ended up figuring it (well, more like working around it) shortly after posting the issue.

**Comment by jarioksa** [comment]
How do you figure that we know about the structure of your data if you do not tell it? That said, when I look at the output image you posted, it looks like site constraints could have been something you were looking for. At least they only take a limited number of values which may be what you think as sites.
