### ISSUE TITLE
calculating centroids for a two way combination

### ISSUE THREAD

**Issue by aguilart** [vegandevs/vegan#417]
Hello, just for visualization, I want to plot the centroids of a PCoA (or an NMDS) from a multivariate dataset that comes from two-factorial experiment desing. That is, I have lab based microbial community data (relative abundances) coming from an experiment following a two factorial design.

I plotted all the data using ggplot by extracting the coordinates of the first two axis using the `scores` function. But to simplify it, I would like to see only the centroids per treatment combination. Using envfit I get the centroids for each "main" factor:

`en_pco <-envfit(spec.pco~Treatment, data= OTU_abundance6, permutations = 999, na.rm = TRUE)`

`en_pco$factors$centroids`

<pre style='color:#000000;background:#ffffff;'>                          Dim1         Dim2
TreatmentControl  <span style='color:#008000; '>0.0005378242</span> <span style='color:#808030; '>-</span><span style='color:#008000; '>0.002919174</span>
TreatmentDrought <span style='color:#808030; '>-</span><span style='color:#008000; '>0.0005378242</span>  <span style='color:#008000; '>0.002919174</span>
</pre>

But, I realize that these centroids are actually means of the first two axis:

`
temp_pco %>% 
     group_by(Treatment) %>% 
     summarise_at(c("Dim1","Dim2"),mean)
`

<pre style='color:#000000;background:#ffffff;'> Treatment      Dim1     Dim2
  <span style='color:#808030; '>&lt;</span>chr<span style='color:#808030; '>></span>         <span style='color:#808030; '>&lt;</span>dbl<span style='color:#808030; '>></span>    <span style='color:#808030; '>&lt;</span>dbl<span style='color:#808030; '>></span>
<span style='color:#008c00; '>1</span> Control    <span style='color:#008000; '>0.000538</span> <span style='color:#808030; '>-</span><span style='color:#008000; '>0.00292</span>
<span style='color:#008c00; '>2</span> Drought   <span style='color:#808030; '>-</span><span style='color:#008000; '>0.000538</span>  <span style='color:#008000; '>0.00292</span>
</pre>

This would mean that one could just calculate the mean per treatment combination on the two axis to get the centroids per group, right?

Sth like:

`
temp_pco %>% 
    group_by(Treatment,Plant) %>% 
    summarise_at(c("Dim1","Dim2"),mean)
`

**Comment by jarioksa** [comment]
Yes, for unweighted methods they are simple means (and for CA/CCA they are weighted means).
