### ISSUE TITLE
betadisper with blocks

### ISSUE THREAD

**Issue by jullee** [vegandevs/vegan#424]
We are wanting to run the betadisper command alongside adonis2. We've figured out how to control our permutations in adonis2 to account for blocks in our experimental design but have not figured out how to set up the corresponding structure when running betadisper.

Our code: 
```
# the permanova with permutations controlled for the blocking factor; where distanceClass has three levels

samp<-dat[,c(6:19)]
perm<-how(nperm=9999)
setBlocks(perm)<-with(dat, Site)
adonis2(samp ~ distanceClass, data=dat, permutations = perm)

# the dispersion test

group_dist<- dat$distanceClass
dis <-vegdist(samp,method="bray")
mod<- betadisper(dis, group_dist)
```

Is it appropriate to run the adonis2 function with controlled permutations but to only specify the main factor of interest in the betadisper test? Or is there a way to account for the blocks in the betadisper test?

I'm hoping this can help us sort out why an NDMS qualitatively reveals similar centroids but very different spread around the centroids of our three distanceClass groups but the betadisper result suggests no significant differences in dispersion...(our permanova is signficant).

**Comment by gavinsimpson** [comment]
See `?permutest.betadisper` which has a `permutations` argument that you can use in the same way as `adonis2()`.

**Comment by jullee** [comment]
Thank you! We are new to this method and missed that!
