### ISSUE TITLE
Installation trouble (/bin/usr/ld: cannot find --llapack and -lblas)

### ISSUE THREAD

**Issue by Mataivic** [vegandevs/vegan#425]
Hello,

I just updated my laptop to Ubuntu 18, and R had been totally uninstalled. After reinstalling R and Rstudio, when trying to install vegan, I got the following error :

```
/usr/bin/ld : cannot find -llapack
/usr/bin/ld : cannot find -lblas
collect2: error: ld returned 1 exit status
/usr/share/R/share/make/shlib.mk:10: recipe for target 'vegan.so' failed
make: *** [vegan.so] Error 1
ERROR: compilation failed for package ‘vegan’
* removing ‘/home/mvictor/R/x86_64-pc-linux-gnu-library/4.1/vegan’
```

Is there any known solution ?

Thanks.

**Comment by jarioksa** [comment]
It seems that you try to install **vegan** from source files, but you do not have tools to build binary package from the source. I think in Ubuntu you should do something like
```sh
sudo apt install build-essential
sudo apt-get install libblas-dev liblapack-dev
```
Specifically, you need both the build tools and the ability to link to BLAS and Lapack (that was the error message), and for this you need to install their `dev` package. There may be some  other packages you need, but check your OS documentation if these are not enough.

**Comment by Mataivic** [comment]
I ran these two commands and it worked ! Thanks a lot.

**Comment by jen-dev-basesolve** [comment]
Thanks @jarioksa , I had been searching a lot to solve the issue, your solution worked.

**Comment by lumigone** [comment]
Thank you! I had been struggling with the same problem and this worked! Thank you very much!
