### ISSUE TITLE
Independent Variables in adonis2 formulas cannot be called grouping

### ISSUE THREAD

**Issue by jfsmenezes** [vegandevs/vegan#431]
Hi, 

I was using adonis2 in  vegan_2.5-7 (R v. 4.1.0) and it seems that independent variables cannot be called "grouping". I managed to replicate this bug in a minimal example:

```
distance = dist(1:100)
grouping = sample(letters[1:2],100,replace=T)
othername = grouping
adonis2(distance ~ grouping)
adonis2(distance ~ othername)
```

The first run of adonis2 yield an error:

```
Error in model.frame.default(delete.response(terms(formula))) : 
  object is not a matrix
```

Meanwhile, the second outputs a normal result:

```
Permutation test for adonis under reduced model
Terms added sequentially (first to last)       
Permutation: free
Number of permutations: 999

adonis2(formula = distance ~ othername)        
          Df SumOfSqs      R2      F Pr(>F)    
othername  1      844 0.01012 1.0024  0.346    
Residual  98    82481 0.98988
Total     99    83325 1.00000
```

I couldn't find any evidence of this bug on the help docs or on the issues here. So I tought I should let you guys known.

**Comment by jarioksa** [comment]
This is a scoping issue: if `data` argument is missing, the independent variable cannot be any **R** function name (for instance, `distance ~ sort` triggers the same error). The fix is obvious, but I need to check that the fix does not break any other behaviour. Putting your variables in a data frame and using a `data=` argument should fix the problem.

**Comment by jarioksa** [comment]
This seems to fail in the current release version (2.5-7), but to work in the current development version (2.6-0). I have no plans to publish further versions of 2.5-x, but the next release would be in 2.6-x. You choices are either to use **vegan** 2.6-0 from github, or use the `data=` argument in 2.5-7.
