### ISSUE TITLE
Adonis2 interactions(*) formula and F.Model -Inf

### ISSUE THREAD

**Issue by sarpiens** [vegandevs/vegan#432]
Hello, 

I have a Aitchison distance matrix (CLR Transformation+Euclidean distance), called temp_d, derived from 16S based data. I have various groups, and I wanted to analyze their variables with a PERMANOVA for feces transplant. The variables shown are  host(species from which the samples were obtained), and feces_host (species form which the input feces came from). I have try both default, by term, and by margin, but I need help to understand the results.

When using by margin:
![adonis_marging](https://user-images.githubusercontent.com/49655743/129204786-e6e406f7-4e9f-4a0e-abdf-d0e8fd88111c.png)

When using including interactions(*) in the model formula, only the interaction term appears and F statistic=-Inf (I don't understand the meaning of this -Inf for the F statistic), but not the individual terms. However when I do it using only interactions(:), or only terms(+), it works, but not when terms and interactions are both included in the model.

When using the default:
![adonis](https://user-images.githubusercontent.com/49655743/129205360-861dc0a8-52ce-404f-a0c9-0c7fa1737a49.png)

 When using including interactions(*) in the model formula, only the terms appear, but not the  interaction term, being the result identical to use only (+). However when I do it using only interactions(:), or only terms(+), it works, but not when terms and interactions are both included in the model.

Thanks in advance for any help!

**Comment by jarioksa** [comment]
About that _F_ =&minus;&infin;: The _F_ is based on zero change in sum of squares with zero degrees of freedom, and it will involve term 0/0 so that the result should strictly be `NaN`  (Not a Number). However, the change in sum of squares is calculated within the function and it may not (and usually is not) strictly zero due to round-off errors. In one test I got it as &minus;6&times;10<sup>-10</sup> and dividing by 0 gives &minus;&infin;.

**Comment by sarpiens** [comment]
Hello, again I have another doubt about interpreting R2 Values when using the byterm or bymargin mode. Following with the above example, imaging that I have "host" and "feces_host" variables and I repeat the adonis2 byterm or bymargin with only one variable. Would the resulting R2 values be comparable?

For example,
adonis2(host) -> R2= 0.5
adonis2(feces_host) -> R2=0.4

Would be the  the variance that "host" explains by its own  > than "feces_host"?
Or the correct way to compare them will be using a marginal model with the two variables?
