### ISSUE TITLE
Code contradicts docs for betadisper (dealing with negative values)

### ISSUE THREAD

**Issue by EvoArt** [vegandevs/vegan#434]
https://github.com/vegandevs/vegan/blob/e304eed5da6a4aa895fa5c1304b0ace27ba2ac4e/R/betadisper.R#L131
Hi there
In the docs it says that you take the absolute value of pos - neg before taking the square root (apparently the same as Permdisp2). Which is obviously different from taking the real part after after calculating the square root. Is this the preferred method now?

Thanks

**Comment by jarioksa** [comment]
When I read the documentation (`help(betadisper)`) , I found the following:
   
     The distance to its centroid of a point is

     z[ij]^c
       = sqrt(Delta^2(u[ij]^+, c[i]^+) - Delta^2(u[ij]^-, c[i]^-)),
     
     where Delta^2 is the squared Euclidean distance between u[ij], the
     principal coordinate for the jth point in the ith group, and c[i],
     the coordinate of the centroid for the ith group. The
     super-scripted ‘+’ and ‘-’ indicate the real and imaginary parts
     respectively. This is equation (3) in Anderson (2006).  If the
     imaginary part is greater in magnitude than the real part, then we
     would be taking the square root of a negative value, resulting in
     NaN, and these cases are changed to zero distances (with a
     warning). This is in line with the behaviour of Marti Anderson's
     PERMDISP2 programme.

What you refer as a documentation is a comment in the code, and you were very selective in quoting the code. If you also take the next comment line, you have:
```r
        ## Negative squared distances give complex valued distances:
        ## take only the real part (which is zero). Github issue #306.
```
which accords the code. (However, not all comments are always updated with later changes in code: they are not regarded as a part of documentation and can become stale.)

The code was changed like this in 2019 after discussion in issue #306. Please consult that issue for details.

**Comment by EvoArt** [comment]
Apologies, I was referring to this : "This is equation (3) in Anderson (2006). If the imaginary part is greater in magnitude than the real part, then we would be taking the square root of a negative value, resulting in NaN. Function takes the absolute value of the real distance minus the imaginary distance, before computing the square root. This is in line with the behaviour of Marti Anderson's PERMDISP2 programme" which I found here https://www.rdocumentation.org/packages/vegan/versions/2.4-2/topics/betadisper the top Google hit for betadisper. So in fact I was reading out of date docs! Thank you.

**Comment by EvoArt** [comment]
Thank you for promptly pointing me in the right direction. I am trying to write some similar code, but was struggling to reconcile Martin Anderson's papers  the (wrong as it happens) docs and the code on GitHub.
