### ISSUE TITLE
Adonis - how to calc the Sums of Squares using the Adonis output

### ISSUE THREAD

**Issue by MatS792** [vegandevs/vegan#439]
Hi all,
is there a way to get from the Adonis() function a matrix that contain the Sums of Squares or other values that are involved in the R squared calculation ?
I am trying to compare the "variance explained" by two adonis calculated on the same matrix distance but with different grouping strategy. 
In other words:
**matrix.dist** is calculated before running adonis.
**grouping_1** is the column within **my_dataset** with one type of grouping.
**grouping_2** is the column within **my_dataset** with an other type of grouping.
The function I used:
adonis1 <- adonis(matrx.dist ~ grouping_1, data = my_dataset, na.action = FALSE, perm = 9999)
adonis2 <- adonis(matrx.dist ~ grouping_2, data = my_dataset, na.action = FALSE, perm = 9999)

Checking within **adonis1** (for example),  I found **coef.sites** which potentially could be the matrix that I'm looking for but I am not sure if coef.sites is the right one. 
Can you help me?

**Comment by jarioksa** [comment]
The `adonis2` (the currently supported version) has column `SumOfSqs` in its output. This stands for "sums of squares". Did you ask about this? If you mean something else, please explain. [Checked in the current release 2.5-7 and the latest development version 2.6-0.]
