### ISSUE TITLE
pretreatment to phyloseq object prior to beta diversity

### ISSUE THREAD

**Issue by marwa38** [vegandevs/vegan#442]
Hello 
Do you advise or recommend making any formating for the phyloseq object prior to beta diversity?

**Comment by jarioksa** [comment]
I have no idea what are **phyloseq** objects. Better ask **phyloseq** developers.

**Comment by marwa38** [comment]
I am not asking about phyloseq I am asking about microbiota datasets whatever the form is!

**Comment by EDiLD** [comment]
Some guidance view focus on microbio can be found here: https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.13536

I don't think that there is a one fits all method. It depends on your data, questions, methods...
