### ISSUE TITLE
Morisita index error in vegdist

### ISSUE THREAD

**Issue by amc228** [vegandevs/vegan#444]
I am trying to calculate a Morisita index using vegdist, using a species abundance matrix that looks like so:

| sp1| sp2 |sp3|sp4|
| ------------- | ------------- | ------------- |------------- |
| 0  | 4  |0  | 1  |
| 0  | 3  | 2  | 1  |
| 1  | 3  |1  | 6  |

When I run distm<-vegdist(df, method='morisita') I get the following error:

"Warning message: In vegdist(x, method = "morisita", na.rm = TRUE) :   missing values in results "

The output looks like so:
|1|2|3|4|5|6|
|------------- |------------- |------------- |------------- |------------- |-------------- |
|NaN||||||

summary(distm) says that all values in the distance matrix generated are NAs:

|Min. 1st Qu.|Median|Mean 3rd Qu.|Max.|NA's|
|------------- |------------- |------------- |------------- |------------- |
|0|0|0|0|123873|

Checks so far:
- all values in the species abundance matrix are integers (as I understand the morisita index requires this)
- there are no 'NAs' or negative values in the species abundance matrix. There are no 'missing values'. 
- changing na.rm to FALSE produces the same result
- all other indicies work - it is only morisita that produces this error

Happy to share the real data if anyone is interested - I'm really confused as to what could be causing this error.

**Comment by jarioksa** [comment]
I cannot reproduce the problem with your data:
```r
library(vegan)
m <- matrix(c(0,0,1,4,3,3,0,2,1,1,1,6), 3, 4)
m
#     [,1] [,2] [,3] [,4]
#[1,]    0    4    0    1
#[2,]    0    3    2    1
#[3,]    1    3    1    6
vegdist(m, "morisita") ## this will be OK:
#          1         2
#2 0.0000000          
#3 0.2941176 0.1326531
```
I know Morisita will fail sometimes (just look at its formula: it must fail sometimes), but it works with your example.
