### ISSUE TITLE
bioenv error: "Error in x$models[[i]] : attempt to select less than one element in get1index"

### ISSUE THREAD

**Issue by pauGuas** [vegandevs/vegan#454]
Hi, I am running bioenv to find environmental variables (continuous measurements) that impact the microbiome (phyloseq object).  

Here is my code:
```
ps <- readRDS("ps.rds")
keepvariables <- which(sapply(sample_data(ps), is.numeric))
ps_sd<- data.frame(sample_data(ps))[keepvariables]

veganotu <- function(physeq) {
  require("vegan")
  OTU <- otu_table(physeq)
  if (taxa_are_rows(OTU)) {
    OTU <- t(OTU)
  }
  return(as(OTU, "matrix"))
}

bioenv(veganotu(ps) ~ TSS + Ammonia + Mg + pH, ps_sd)
```

I am getting this error:
Error in x$models[[i]] : 
  attempt to select less than one element in get1index

Does anyone know what this means?

**Comment by jarioksa** [comment]
So many things that I cannot reproduce, but what does `str(ps_sd)` or `summary(ps_sd)` look like? I have no idea where this error comes from, but issuing `traceback()` after the error will show the actual point of error.
