### ISSUE TITLE
How to save pairwise comparison of betadisper as a csv file

### ISSUE THREAD

**Issue by anrongloh93** [vegandevs/vegan#455]
Hi there, I am trying to save the pairwise comparison for my betadisper results as a csv file. However i get the error code which I do not understand : 
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"permutest.betadisper"’ to a data.frame

My initial codes were :
#Pairwise PERMDISP of all Plat collected from Hantu based on Date
PERMDISP_Plat_Hantu_Date <- betadisper(Plat_Hantu_Bray, Plat_Hantu_dataframe$Date)
PWPD_Plat_Hantu_Date <- permutest(PERMDISP_Plat_Hantu_Date, pairwise = TRUE, permutations = 9999)

with the results"
Pairwise comparisons:
(Observed p-value below diagonal, permuted p-value above diagonal)
          Jan_2019  Jan_2020  Jul_2019  Mar_2019  May_2019  Nov_2019 Sep_2019
Jan_2019           0.9095000 0.7884000 0.2486000 0.1206000 0.0272000   0.3076
Jan_2020 0.9138881           0.7244000 0.2516000 0.2084000 0.0410000   0.3010
Jul_2019 0.7864155 0.7237769           0.3723000 0.0640000 0.0471000   0.4263
Mar_2019 0.2479307 0.2560074 0.3748513           0.0051000 0.1416000   0.9345
May_2019 0.1180489 0.2012789 0.0648550 0.0045068           0.0002000   0.0196
Nov_2019 0.0276606 0.0383779 0.0446314 0.1399266 0.0002723             0.2862
Sep_2019 0.3126952 0.3058734 0.4327434 0.9416200 0.0197414 0.2889694 

but the error message for this code to save as a csv:
write.csv(PWPD_Plat_Hantu_Date, file= 'PWPD_Plat_Hantu_Date.csv')

Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"permutest.betadisper"’ to a data.frame

**Comment by gavinsimpson** [comment]
You can't just save an arbitrary list to a CSV file as it isn't rectangular in shape.

What you want is to extract the pairwise p value table from the list you saved, and pass that to `write.csv()`

**Comment by anrongloh93** [comment]
> 

Hi Gavin,

Thank you very much for the help! It worked perfectly. May I also check from the output what does the 'observed' represents here? 

Appreciate it!

**Comment by gavinsimpson** [comment]
I should probably change that; it is the theoretical p value based on an assumption that the sampling distribution of the test statistic under the null hypothesis is a *t* distribution. This contrasts with the permutation p value where we generate a sampling distribution of the test statistic under the the null by a permutation test.

**Comment by anrongloh93** [comment]
Hi Gavin,

Thanks alot for the explanation it was very helpful! Appreciate your time taken to help me out!
