### ISSUE TITLE
RDA always displays only part of the env factors

### ISSUE THREAD

**Issue by Emmamu** [vegandevs/vegan#456]
Hi all

I have 11 environmental variables to associate with genetic structure (allele frequencies) using RDA. But no matter how I arranged the order of the 11 factors, RDA always display results of the first 8. Anyone knows what was wrong and how to fix the problem?

here're are the files and code I used:
`GenData = read.table("GenData.txt", header = T)`
`GeogData = read.table("GeogData.txt", header = T)`
`RDA_full<- rda(GenData, GeogData)`
`plot(RDA_full)`
`summary(RDA_full)`
[GenData.txt](https://github.com/vegandevs/vegan/files/7807723/GenData.txt)
[GeogData.txt](https://github.com/vegandevs/vegan/files/7807725/GeogData.txt)

**Comment by jarioksa** [comment]
You have nine observations, and eleven env factors. You overfit your data:  you cannot have more predictors than you have observations.

In fact, you could have a complete fit with a random data:
```r
> randomdata <- matrix(runif(9*11), 9, 11) # same dims as in your GeogData
> rda(GenData, randomdata)
Call: rda(X = GenData, Y = randomdata)

              Inertia Proportion Rank
Total           1.907      1.000     
Constrained     1.907      1.000    8
Unconstrained   0.000      0.000    0
```
As you see, with random predictors you have zero unconstrained (residual) variance, and the solution has rank 8 – that means, only 8 of 11 random predictors were used.

You will have the same problem with any normal linear method. You can check what you would get in linear regression:
```r
lm(GenData[,1] ~ ., GeogData)
```

There are two alternative solutions:
1. Collect more data: 9 observations is not much for multivariate analysis.
2. Do not use so many predictor variables. With 9 observations 3 is many.
