### ISSUE TITLE
What is the MAT in`ctrace <- function(MAT) sum(MAT^2)`? 

### ISSUE THREAD

**Issue by jolespin** [vegandevs/vegan#465]
Here is the permalink: 
https://github.com/vegandevs/vegan/blob/47e9fc3c674fea5026abe51c55ddceb60771448d/R/procrustes.R#L14

I'm trying to figure out how this implemented so I can recreate a plot in Python and understand the actual maths behind it (easier for me to read in Python). 

I'm confused about this line: 
` ctrace <- function(MAT) sum(MAT^2)`

What is this doing exactly? I couldn't find a `MAT` object in the function.

Is it similar to `traceTA` in this SO answer? 
https://stackoverflow.com/a/18927641/678572

Currently a work in progress to understand your code but it's coming along: 
https://stackoverflow.com/questions/70870829/how-to-plot-rs-veganprocrustes-using-python-scipy-numpy-and-matplotlib

**Comment by gavinsimpson** [comment]
`MAT` is what we use to refer to the object passed to the `ctrace` function. For example:

https://github.com/vegandevs/vegan/blob/47e9fc3c674fea5026abe51c55ddceb60771448d/R/procrustes.R#L19-L20

So `MAT` is an argument that we pass `X` and `Y` to. `ctrace()` is just element-wise squaring the matrix `MAT`, then summing up the elements of `MAT`.

In R, a matrix is basically a vector with some information baout the size of each dimension (how many rows and columns). You would need to find the equivalent Python operation to square all the elements of a matrix and then find out how to sum the elements of a matrix. The steps are basically:

```r
r$> m <- matrix(1:9, ncol = 3)                                                  
r$> m                                                                           
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
r$> m^2                                                                         
     [,1] [,2] [,3]
[1,]    1   16   49
[2,]    4   25   64
[3,]    9   36   81
r$> sum(m^2)                                                                    
[1] 285
```

It looks like the equivalent of `sum(MAT^2)` in that Python code you link to is:

```python
    ssX = (X0**2.).sum()
    ssY = (Y0**2.).sum()
```

**Comment by jarioksa** [comment]
If you want to implement Procrustes rotation in Python, you should primarily have a look at Mardia, K.V., Kent, J.T. and Bibby, J.M. (1979). _Multivariate Analysis_, pages 416–419 which gives the mathematics (and there must be many other good books telling the same story). That's where I looked at when I implemented the method. I also had a Fortran implementation but I did not want to transport its twisted logic into R, but did some reading. Translating from R to Python may not give the best code as you may be left with R-isms. I would also have a good look at NumPy which may already have this, or at least it will have all the building blocks.

**Comment by jarioksa** [comment]
A small comment to @gavinsimpson's Python code: do not use float (2.) as the exponent when you have integer power (square): `**` seems to know the difference and do the right thing with integer power: with float power `x**a` the calculation probably translates to exp(_a_ * log(_x_)) but with integer power it translates to _x_ * _x_ or a real square. Fortran has always known the difference, but C, R or several Python alternatives do not. https://docs.python.org/2/library/math.html#power-and-logarithmic-functions

**Comment by jolespin** [comment]
I finally figured out what I was doing wrong. Just in case anyone wants to reproduce the VEGAN implementation of Procrustes using Python's NumPy and SciPy. Here you go: 

```python
# Get X and Y which are the first 2 embeddings
# -------------------------------------------
# X <- scores(X, display = scores, ...)
mds_null = pd.read_csv("https://pastebin.com/raw/c1Zwb4pu", index_col=0, sep="\t")
X_original = mds_null.values
# X_original[:5]
# array([[-0.28600328, -0.23135498],
#        [ 0.00510282, -0.39170001],
#        [ 0.80888622,  1.18656269],
#        [ 1.44897916, -0.18887702],
#        [ 0.54496396, -0.09403705]])

# Y <- scores(X, display = scores, ...)
mds_alt = pd.read_csv("https://pastebin.com/raw/UMGLgXmu", index_col=0, sep="\t")
Y_original = mds_alt.values
# Y_original[:5]
# array([[ 0.2651293 ,  0.09755548],
#        [ 0.17639036,  0.45328207],
#        [-0.16167398, -1.42304932],
#        [-1.44706047,  0.3966337 ],
#        [-0.49825949,  0.15239689]])


# Procrustes in VEGAN
# ----------------
procrustes_result = vegan.procrustes(X_original, Y_original, scale=True, symmetric=False, scores="sites")

# Rotation matrix from VEGAN
A = np.array(dict(procrustes_result.items())["rotation"])
# A
# # array([[-0.98171787, -0.19034186],
# #        [ 0.19034186, -0.98171787]])

# Center the X and Y data
# -----------------------
X_mean = X_original.mean(axis=0)
X = X_original - X_mean
Y_mean = Y_original.mean(axis=0)
Y = Y_original - Y_mean

# # Rotation matrix from SciPy
# ----------------------------
A, sca = orthogonal_procrustes(X,Y)
# A
# array([[-0.98171787,  0.19034186],
#        [-0.19034186, -0.98171787]])


# Manual calculation
# ------------------
# np.linalg.svd returns:
# u{ (…, M, M), (…, M, K) } array
# Unitary array(s). The first a.ndim - 2 dimensions have the same size as those of the input a. The size of the last two dimensions depends on the value of full_matrices. Only returned when compute_uv is True.

# s(…, K) array
# Vector(s) with the singular values, within each vector sorted in descending order. The first a.ndim - 2 dimensions have the same size as those of the input a.

# vh{ (…, N, N), (…, K, N) } array
# Unitary array(s). The first a.ndim - 2 dimensions have the same size as those of the input a. The size of the last two dimensions depends on the value of full_matrices. Only returned when compute_uv is True.

XY = np.dot(X.T, Y) # crossprod(X,Y)
U,s,Vh = np.linalg.svd(XY)
V = Vh.T
A = np.dot(V, U.T)
# A
# array([[-0.98171787, -0.19034186],
#        [ 0.19034186, -0.98171787]])

# Reproduce the Yrot object
# -------------------------
scale = True
symmetric = False

# Yrot from VEGAN
Yrot = np.array(dict(procrustes_result.items())["Yrot"])
# Yrot[:5]
# array([[-0.20919556, -0.12656386],
#        [-0.07519809, -0.41418755],
#        [-0.09706039,  1.23572329],
#        [ 1.29483042, -0.098617  ],
#        [ 0.44844991, -0.04740275]])

# NumPy implementation
# ctrace <- function(MAT) sum(MAT^2)
def ctrace(MAT):
    return np.sum(MAT**2)

# if (scale) {
#     c <- sum(sol$d)/ctrace(Y)
if scale:
    c = np.sum(s)/ctrace(Y)

# Yrot <- c * Y %*% A
Yrot = c * np.dot(Y,A)
Yrot[:5]
# array([[-0.20919556, -0.12656386],
#        [-0.07519809, -0.41418755],
#        [-0.09706039,  1.23572329],
#        [ 1.29483042, -0.098617  ],
#        [ 0.44844991, -0.04740275]])
```

Now I finally understand how the analysis works haha.
