### ISSUE TITLE
[Question] How are the residuals calculated in procrustes? 

### ISSUE THREAD

**Issue by jolespin** [vegandevs/vegan#466]
I'm looking at the source code [here](https://github.com/vegandevs/vegan/blob/83fd020085d6f294ea48496f91564600795c049c/R/summary.procrustes.R): 

```R
"summary.procrustes" <-
function (object, digits = getOption("digits"), ...) 
{
    ans <- object[c("call", "ss")]
    n <- nrow(object$Yrot)
    k <- ncol(object$Yrot)
    ans$resid <- residuals(object)
    rmse <- sqrt(object$ss/n)
    ans$n <- n
    ans$k <- k
    ans$rmse <- rmse
    ans$rotation <- object$rotation
    ans$translation <- object$translation
    ans$scale <- object$scale
    ans$digits <- digits
    class(ans) <- "summary.procrustes"
    ans
}
```

I'm not understanding how the residuals are being calculated? What is the `observed` and `predicted` in this case?

**Comment by jarioksa** [comment]
```r
`residuals.procrustes` <-
  function (object, ...)
{
  distance <- object$X - object$Yrot
  resid <- rowSums(distance^2)
  sqrt(resid)
}
```
This gives Euclidean distance between observed and Procrustes rotated scores. `Yrot` is calculated in `procrustes`.

**Comment by jolespin** [comment]
Thanks a lot! I'll be able to explain the results much better now.

**Comment by jolespin** [comment]
Apologies to ping you again but I had a question about the symmetric argument and the protest function: https://stats.stackexchange.com/questions/563911/what-is-the-difference-between-symmetric-and-non-symmetric-in-procrustes-protest

Since this is more theoretical and less about the vegan package, I posted it on stats.stackexchange 

Not sure if you had any insight on this, but wanted to send it over just in case. 

Cheers
