### ISSUE TITLE
Beta diversity results changed suddenly

### ISSUE THREAD

**Issue by pauGuas** [vegandevs/vegan#467]
Hi, I am trying to re-run adonis on my phyloseq data.  Previously, my results were 0.001 for "season", but now I am getting 0.86. I haven't changed anything on my data.  Then, when I try to do pairwise.adonis, I am getting this error 

Error in as.matrix(x)[factors %in% c(as.character(co[1, elem]), as.character(co[2,  : 
  (subscript) logical subscript too long

Does anyone know what could be happening?

**Comment by yangzhuzhu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by gavinsimpson** [comment]
@yangzhuzhu That you signed up to watch all correspondence on this repo **and** then turned on an auto-reply is totally inconsiderate. You are blocked from posting Issues until

1. you email me directly to assure me you have either stopped watching this repo or set the Watch option to Participating or Mentions **and** you are not using an email address as your GH account that you also have a vacation autoresponder on, and
2. you undertake to not repeat this

Trying to triage Issues here is becoming a job in and of itself with all the questions being posted as Issues recently, without other people making that job harder.
