### ISSUE TITLE
CCA error: "Error in rowSums(X) : 'x' must be numeric"

### ISSUE THREAD

**Issue by pauGuas** [vegandevs/vegan#470]
Hi, I am running a CCA on phyloseq data. 

`ccamodel=cca(otuDF ~ pH, data=sdDF)`

otuDF: dataframe of my OTU table (167 obs of 16182 numeric variables)
rownames(otuDF) = sampleID

sdDF: dataframe of my sample data (167 obs of 14 numeric variables)
rownames(sdDF) = sampleID

I get "Error in rowSums(X) : 'x' must be numeric".
I also get the same error when I try rowSums(otuDF) or otuDF <- otuDF[rowSums(otuDF) > 0,].

Does anyone know what could be wrong?

**Comment by pauGuas** [comment]
Wow, literally 2 minutes after I posted this I figured it out. 

Step 1) Set rownames to SampleID
rownames(otuDF) <- otuDF[,1]

Step 2) Remove SampleID column because it is a character
otuDF$SampleID <- NULL

**Comment by gavinsimpson** [comment]
@pauGuas with these basic questions, please don't ask them here. instead consider using the StackOverflow website. Or use the Discussion tab here on GitHub. Dealing with questions in what are typically bug reports involves work for the maintainers, even if it's just to triage these things and close them.

Also, consider asking the *physloseq* maintainers about issues to do with data from that package.
