### ISSUE TITLE
add as.dist in varpart?

### ISSUE THREAD

**Issue by m-urvoy** [vegandevs/vegan#497]
Hello,
I wanted to report a dumb mistake I made that could probably be easily avoided: I used dbrda and varpart with a distance formatted as a full matrix (instead of a lower triangle). Both functions worked without warning but varpart gave weird values (higher explained variance than dbrda). I (eventually) realized that the problem came from the matrix format and added an "as.dist" that fixed everything.
Perhaps it would be nice to add this in the varpart source code? It seems already present in the dbrda source code.
In any case, thank you very much for this package!
Marion

**Comment by jarioksa** [comment]
Accepts now similar input as `dbRDA` and allows distances in symmetric square matrices.
