### ISSUE TITLE
Issue with rda()

### ISSUE THREAD

**Issue by souvanikmaity** [vegandevs/vegan#511]
I am trying to use rda() analysis, but only the first 10 variables are explained and plotted on the biplot. When I change the sequence of variables, the same things happen, i.e., the first 10 variables are considered only, and the constrained proportion is also the same in different sequences of variables. I have removed some variables using correlation values above 0.8, but the problem still persists.
I need your expertise. Please help.
Thank You

**Comment by jarioksa** [comment]
I need  more information, and preferably a reproducible example.

**Comment by souvanikmaity** [comment]
Sir,
I have attached all the files.

**Comment by EDiLD** [comment]
Note that attachments via email do not arrive on github. Please provide them there directly.

**Comment by souvanikmaity** [comment]
[Files.zip](https://github.com/vegandevs/vegan/files/8597517/Files.zip)

**Comment by jarioksa** [comment]
Your x-variates are linearly dependent, and only ten can be used. This was told in the printed output. One example in your example gave the following result:
```r
Call: rda(formula = y ~ vx1 + vx2 + vx3 + vx4 + vx5 + vx6 + vx7 + vx8 +
vx9 + vx10 + vx11 + vx12 + vx13 + vx14 + vx15 + vx16 + vx17 + vx18 +
vx19 + vx20 + vx21 + vx22 + vx23 + vx24 + vx25 + vx26 + vx27 + vx28 +
vx29 + vx30 + vx31 + vx32 + vx33 + vx34 + vx35, data = x, scale = T)

              Inertia Proportion Rank
Total         24.0000     1.0000     
Constrained   12.4636     0.5193   10
Unconstrained 11.5364     0.4807   22
Inertia is correlations 
Some constraints or conditions were aliased because they were redundant
```
Please note the last line on redundant variables. These variables can be expressed with help of other variables in the model, and contain no independent information. The names of redundant variables are:
```r
> alias(rda, names.only=TRUE) # rda is the name of result object in your example data
 [1] "vx11" "vx12" "vx13" "vx14" "vx15" "vx16" "vx17" "vx18" "vx19" "vx20"
[11] "vx21" "vx22" "vx23" "vx24" "vx25" "vx26" "vx27" "vx28" "vx29" "vx30"
[21] "vx31" "vx32" "vx33" "vx34" "vx35"
```
Dropping argument `names.only=TRUE` will give the defining relationships in your data, but it is too long to be shown here. However, only 10 variables can be kept and 25 must be ignored with your data.

This is not a **vegan** feature, but a feature of your data. You will get similar output with any linear statistical model, such as in standard regression analysis. Try:
```r
lm(y[,1] ~ ., data=x)
```
which will give regression coefficient `NA` for most (25) variables, and only 10 coefficients that can be estimated with your data.

**Comment by souvanikmaity** [comment]
I have worked based on your suggestions. Thank you Sir for giving me your
valuable time.
