### ISSUE TITLE
adonis() documentation

### ISSUE THREAD

**Issue by martyoh** [vegandevs/vegan#515]
Just wondering if line 168 in vegan/man/adonis.Rd should actually be

`with(dat, ordiellipse(mod, NO3, kind = "ehull", label = TRUE))
`

**Comment by jarioksa** [comment]
`adonis` is currently deprecated, also in the latest CRAN release vegan 2.6-2. Its documentation no longer has that line. The new function is `adonis2` and it does not have such an example.
