### ISSUE TITLE
db-RDA plot: overcoming limit of 80 species and repel the species labels

### ISSUE THREAD

**Issue by magibc** [vegandevs/vegan#522]
Hi,

I'm trying to perform a db-RDA with my microbiome data that I have 201 different species towards 220 samples.

Nevertheless, when I plot the biplot db-RDA I discovered that the species appears as dot points (without species name) but if I subset my original dataset to 80 species (81 does not work) then the biplot db-RDA obtained prints the species names.

It is possible to overcome this situation and print in the plot all the species labels or some of them according to their value in CAP axis? In addition, it is possible to repel the labels to avoid overlapping?

Thanks on advance for your time and help,
Maggie
```
plot_subset <- capscale(species_subset ~ antibiotic + Diagnosis , data=meta_data_subset , distance="bray", add=T)
plot(plot_subset, display=c("sp","bp"))
```

vegan R version: 2.6-2

**Comment by jarioksa** [comment]
Use `type = "t"` for text. The default is to use text (`type = "t"`) if you don't have too many things to plot, and then switch to points (`type = "p"`), but you can overrule this by setting the `type`.

**Comment by jarioksa** [comment]
As to repel: it is not available in **vegan**: the labels are exactly at the correct location of their coordinates, and repelling would move them to wrong place. However, have a look at the vegan-FAQ section "How to avoid cluttered ordination graphs?" (you can use `browseVignettes("vegan")` to see the FAQ if they are not directly available in your session). Function `ordipointlabel` is closest to "repelling": it shows both points and their labels keeping points in exact locations but moves labels to avoid overwriting.

**Comment by magibc** [comment]
Many thanks @jarioksa.
Solved both things!!!

David.
