### ISSUE TITLE
Using specpool no "se" for jack2 returns

### ISSUE THREAD

**Issue by dannyvelezv** [vegandevs/vegan#526]
Hi,

Is there any statistical reason why specpool does not returns the "se" for jack2?

Thanks

**Comment by jarioksa** [comment]
I expand: it may be that the original paper had equations for SE of jackknife-2, but for some reason I did not implement them. A reason could be that the code would be too ugly. However, I recycled these papers long time ago and cannot check. If you find the paper, and think that SE can be implemented, I'll be glad to merge that in vegan. Even when I think that *all* these classic methods are flawed and should not be used.

**Comment by dannyvelezv** [comment]
Dear Dr. Oksanen,

Thank you for paying attention to my question! I am sad to say that I do not have the skills to implement it in a R code. I was just playing with the Vegan and noticed that there was no SE for Jack2, then I thought that maybe there were some kind of statistical reasons for that. 

What methods do you recommend insted of the classical methods?

Cheers!

**Comment by jarioksa** [comment]
There are many, and some of them are popular. I may be partial (actually I am partial), but check this. https://github.com/alessandrozito/BNPvegan

**Comment by jarioksa** [comment]
I expand a bit more: **vegan** has function `rrarefy` that gives you random rarefied community. That is, the community you have, but with reduced number of individuals. That also means lower number of species. This function only makes sense if you have a count (individual) sample of your community. The test is here: if you take a random-rarefied (`rrarefy`)  sample of your observed community, and use these ´specpool()` methods on them, you should get the original non-rarefied number of species or larger. If you take random rarefied samples of different sizes, they should all give you the same the  number of species pool or total number of species (including unseen species). I have tired this many times with several data sets, and this never works. I think many of these fancy new methods fall in the same trap: if you have a series of random rarefied samples, these do not give the same "final" number of species or the observed number of species in your data set. However, try yourself and feel free to disagree with me. I think the most popular package is iNext. Try with that. I have never tried, but when I have looked at its ads, it looks much sounder than the legacy methods I put in **vegan** in 2003 (19 years ago).

**Comment by dannyvelezv** [comment]
Thank you! BNPvegan seems to be really nice to use! 
Last question, any method using just incidences that you would like to reccomend?
I saw Chao in iNext.
