### ISSUE TITLE
random signs in PCoA dimensions

### ISSUE THREAD

**Issue by eprifti** [vegandevs/vegan#529]
Hello,
I'm trying to compare several pipelines that change very slightly in composition. Their PCoA plots should be very close. I notice that the signs of the PCoA coordinates change between them and I was wondering wether there is a way to fix it ?

There are 4 pipelines results and you can see that for the raw facet both results are flipped on the pcoa2 dimension and the flip is also for both facets on pcoa1 dimension

<img width="1703" alt="Screenshot 2022-09-20 at 17 06 34" src="https://user-images.githubusercontent.com/13483898/191294822-d5965119-fbe8-4e30-9d9a-7b88a341170d.png">

best
edi

**Comment by jarioksa** [comment]
It's a feature of eigenvector analysis. There is no way to "fix" it, because sign is arbitrary in eigenvector analysis. You only need to cope with it. One way of coping with the issue is to use Procrustes analysis (`vegan::procrustes()`) in comparisons.

**Comment by eprifti** [comment]
thanks jarioska,
A quick workaround is to flip it by hand by multiplying the coordinates of the given axis with -1.
I was about to check `vegan::procrustes()` thanks for the suggestion.
I'm closing the issue.
