### ISSUE TITLE
method for obtaining "tidy" scores seems broken?

### ISSUE THREAD

**Issue by arne1921KF** [vegandevs/vegan#532]
When exploring a dataset, I noticed the option to obtain "tidy" scores compatible with ggplot2.

I gave it a quick go and got a NULL object back. Restarting the R session and running from a blank environment didn't help. No time to investigate further, and no colleague at hand who can run this on their machine for comparison - sorry for that!

Reproducible example:

```
dca <- decorana(dune)
sc <- scores(dca, display="sites", tidy = TRUE)
```

**Comment by jarioksa** [comment]
Vegan version please (and see https://github.com/vegandevs/vegan/blob/master/inst/NEWS.md, first item).

**Comment by gavinsimpson** [comment]
The example works in the current dev version of **vegan**.

If you need it @arne1921KF, see the installation instructions to install **vegan** from our R Universe repository in the[README](https://github.com/vegandevs/vegan/blob/master/README.md).
