### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by sofocles2000** [vegandevs/vegan#569]
I have a problem with my code, I am doing a PCA with 14 variables, but when I perform the PCA only shows me the 10 first variables. 
This is the code that I´m using. 

columnea_imp_PCA = PCA(columnea_imp1, scale = TRUE)
summary(columnea_imp_PCA)
print(columnea_imp_PCA)

This is the output 
**Variables (the 10 first)**
        Dim.1    ctr   cos2    Dim.2    ctr   cos2    Dim.3    ctr   cos2  
Lco  |  0.622  5.241  0.387 |  0.735 15.728  0.540 |  0.039  0.115  0.001 |
Lef  |  0.697  6.591  0.486 |  0.677 13.344  0.458 |  0.002  0.000  0.000 |
Anco |  0.831  9.364  0.691 |  0.385  4.324  0.148 | -0.102  0.797  0.010 |
Alco |  0.909 11.208  0.827 |  0.285  2.361  0.081 | -0.047  0.171  0.002 |
Lpi  |  0.354  1.698  0.125 |  0.807 18.951  0.651 | -0.016  0.019  0.000 |
pLes |  0.426  2.456  0.181 |  0.457  6.087  0.209 | -0.142  1.562  0.020 |
Cone |  0.222  0.670  0.049 | -0.192  1.076  0.037 |  0.806 50.026  0.650 |
Lfst |  0.312  1.321  0.097 |  0.220  1.415  0.049 |  0.773 46.015  0.598 |
Lpe  |  0.956 12.401  0.915 | -0.006  0.001  0.000 | -0.085  0.562  0.007 |
Ctc  |  0.853  9.853  0.727 | -0.495  7.127  0.245 | -0.060  0.274  0.004

**Comment by jarioksa** [comment]
I can't decrypt your message. Moreover, there is no command `PCA` in **vegan** (or in any other package I know).
