### ISSUE TITLE
Values of S.chao1 & ACE bigger than total_counts

### ISSUE THREAD

**Issue by lynneitelson** [vegandevs/vegan#583]
Hi, 

I have a table of OTU's and how many times they were seen on each media:

![image](https://github.com/vegandevs/vegan/assets/109670658/c312b97d-c3cf-4aaf-a8d8-698e3ead8ffd)

I used the code written below and got strange results. The statistical values of ACE and Chao1 are larger than the total counts (total counts was calculated in the initial excel work sheet by applying =sum to each column). 

What might be wrong?

The results:
 
![image](https://github.com/vegandevs/vegan/assets/109670658/47168d23-4719-4d37-a2d8-965ff487773c)

Thank you! 

The code:

`library("vegan")

#=============upload and fix the table=================#
media_table <- read.csv("Media.csv")

media_table <- subset(media_table, select = ISP2:MA)
media_table$MA <- media_table$ma

#=================Calculations of chao ace & sobs==================#

community <- as.matrix(media_table)

transposed_matrix <- t(community)
chao <- estimateR(transposed_matrix, "chao")
df_chao <- as.data.frame(chao)

write.csv(df_chao1, file = "X:/MichaI_Shared/users/lynne/Experiment/cultivation/chao+ace/df_chao_ace_sobs.csv")
`

**Comment by jarioksa** [comment]
What looks like wrong? Your results cannot be found from your data table, and I have no idea how you got those results. However, the Chao and ACE values *can* be larger than the total count – after all, they are estimates of *unseen* species, and what is unseen is unseen also to total count. I think that for most data sets this happens rarely, but if none of the OTUs has very high counts, and there are many OTUs with count 1 the estimates for unseen species can be very high.

The estimated number of unseen species, or the number of species added to the observed number of species is found from the number of species seen only once (singletons) _a_<sub>1</sub> or twice _a_<sub>2</sub> in `estimateR` as _a_<sub>1</sub> (_a_<sub>1</sub> – 1) / (_a_<sub>2</sub> + 1) / 2. It is easy to see that this can be a large number if there are many OTUs that were seen only on once, or _a_<sub>1</sub> is large and _a_<sub>2</sub> = 0 or small.
