### ISSUE TITLE
Error in adonis: dissimilarities must be non-negative

### ISSUE THREAD

**Issue by otaviolovison** [vegandevs/vegan#587]
Hello!

I am trying to perform PERMANOVA on a Jensen-Shannon divergence matrix calculated from normalized data (clr and tss) and getting this error (title). 
When I use non-normalized data, the adonis2 function runs without error. 

Anyone has an idea why this is happening?

When I run the same process for Bray-Curtis and Jaccard, or even for the JSD from non-normalized data, I have no error, besides the fact that these 3 matrices has negative dissimilarities values in the matrix. 

Thanks in advance!

**Comment by jarioksa** [comment]
Obviously your dissimilarities are negative. There is a threshold of &minus;10<sup>-7</sup> for negative values regarded as zeros, but more negative ones are regarded as an error. If you are sure that these negative values should be regarded as zero, make them so with something like `d[d<0] <- 0` for dissimilarities `d`. This is not bullying, but `adonis2` just cannot cope with negative dissimilarities.

I do not know how you got your dissimilarities. It is sure that Jaccard and Bray-Curtis from **vegan** cannot be negative for non-negative data – and they do not make sense with negative data. If the thing that you call *normalization* produces negative data, you should carefully consider what kind of indices work with them.

**Comment by jarioksa** [comment]
There is no information to proceed on this issue. Please re-open if you think there is a problem, @otaviolovison . However, in this case we need more information.
