### ISSUE TITLE
Error message using vegan and "shannon" index 

### ISSUE THREAD

**Issue by Willowtree72** [vegandevs/vegan#608]
Hi 
Can anyone help wit this error message please?
this is the code I'm using:-
J <- diversity(twice.mega, index='shannon') / log(sum(twice.mega > 0))

The error message is 
Error in diversity(twice.mega, index = "shannon") : 
  unused argument (index = "shannon")

Thank you

**Comment by gavinsimpson** [comment]
> ...how would I work out out what function is masking `vegan::diversity` ?

One way is to ask for the environment of the function using `environment()`. Below it shows that the `diversity` that is first on the search path in my session is the one from the vegan package namespace.

```r
> environment(diversity)
<environment: namespace:vegan>
```

In your session it should show a different namespace or environment, which will be the source of the masking.

**Comment by Willowtree72** [comment]
great thank you !

**Comment by Willowtree72** [comment]
Yes it's showing the source of the masking is igraph - does this effect anything and should I unmask it?
environment(diversity)
<environment: namespace:igraph>
