### ISSUE TITLE
Trying to write a short loop using 'd' function to estimate qD for q = 0,1 and 2

### ISSUE THREAD

**Issue by Willowtree72** [vegandevs/vegan#609]
I'm trying to write a short loop but it's not working..

So using the  ‘d’ function to estimate  qD for q=0,1 and 2. The code I have so far for the short loop is 
qD <- matrix(NA, nrow=nrow(twice.comm), ncol=3)

but I just get NA in all the cells.... 

Then I'm using ...

for(i in 1:nrow(twice.comm)){
+   for(j in 1:3){
+     qD[i,j] <- d(twice.comm[i, ], q=j-1)
+   }
+ }

but the error message is...  Error in d(twice.comm[i, ], q = j - 1) : could not find function "d"

I'd be very grateful if someone can anyone help with this

**Comment by gavinsimpson** [comment]
Vegan doesn't contain any function with the name `d`. Please don't abuse our bug tracker for help requests, especially when those questions are nothing to do with vegan.
