### ISSUE TITLE
CCA/RDA row name order matters

### ISSUE THREAD

**Issue by TJrogers86** [vegandevs/vegan#615]
Hello developers,
Maybe this is something that is written in the description of the tools and I have missed it, but I have recently found that the order of row names matters when preforming constrained ordination. If the row name order differs between my environmental variables and my OTU table, but the number of rows are the same, then I get a completely different (more times than not, terrible) result than when the row names are in the same order between these to data sets. Is this a known issue?

**Comment by jarioksa** [comment]
It is not an issue, but it is the fact, and it has been a fact for 22 years. It was designed so. Row should match a row. How else could it be? Fix your analysis.

**Comment by TJrogers86** [comment]
My mistake. I had erroneously assumed that the function(s) would match row names between the environmental and OTU data frames.
