### ISSUE TITLE
Functions `ordirgl` and `ordiplot3d` no longer seem to be in the package

### ISSUE THREAD

**Issue by aghaynes** [vegandevs/vegan#620]
The intro-vegan vignette mentions the `ordirgl` and `ordiplot3d` functions, but they no longer seem to be a part of `vegan`...? Does the vignette need updating?

https://github.com/vegandevs/vegan/blob/65dce8d72b51adc20b337ef0566f9bf7ae3b111e/vignettes/intro-vegan.Rnw#L159C1-L164C1

**Comment by gavinsimpson** [comment]
They are in package vegan3d; if we don't mention this in the vignette then yes, the vignette needs updating.

**Comment by jarioksa** [comment]
Yes indeed, the functions are mentioned in `vignettes/intro-vegan.Rnw`. The vignette should be updated, and it makes sense to hint to **ggplot2** graphics as well (although **ggvegan** is not yet in CRAN).

**Comment by aghaynes** [comment]
yes, a hint about ggvegan would be great... i reverse engineered a couple of things for a project i'm working on now, including elliptical hulls, which dont seem to be in ggvegan at the moment
