### ISSUE TITLE
cex vegan::ordiplot not respected by plot.(d)c(c)a

### ISSUE THREAD

**Issue by BertvanderVeen** [vegandevs/vegan#656]
I sparingly use vegan::ordiplot, which has a "cex" argument. However, ordiplot calls plot.cca, which does not take a cex argument, so that the behavior of vegan::ordiplot is inconsistent for different methods. Is would be great if plot.cca would also receive a cex argument so that vegan::ordiplot is a bit more consistent across different methods.

**Comment by jarioksa** [comment]
Yes, verified. I'll see this happen. Thanks for your note.
