### ISSUE TITLE
Related to #655 should the wrappers allow partial unconstrained ordination via formula and `Condition()`?

### ISSUE THREAD

**Issue by gavinsimpson** [vegandevs/vegan#662]
Right now we have `pca()`, `ca()`, and `pco()` as wrappers to fitting functions `rda()`, `cca()` and `pco()`. These unconstrained ordination wrappers allow arguments to be passed to the fitting function, so partial ordination is possible but only via the matrix-element interface.

Should we turn the wrappers for unconstrained ordination into S3 generics with the currently-implemented functions becoming the default method and then allowing a formula interface of the form `y ~ 1 + Condition(x + z)`?

I know you can you just use `cca()` etc for this, but the same argument as the one given in #655 applies.

If we allow this, should we check that the formula only contains `1` (or `0`?) and `Condition()`? so that it really is an unconstrained model? Or should we allow abuse of the wrappers to pass covariates but check the object returned by `cca()` etc for presence of covariates (constraints) and if present return that object unmodified, so that we only return a `"ca"` (etc) classed object if the model has no covariates (constraints)?

**Comment by gavinsimpson** [comment]
@jarioksa Yes to all that; but the question at hand was whether to allow the new wrappers to use `Condition()` via a formula to fit partial CA etc.

**Comment by jarioksa** [comment]
@gavinsimpson Fair enough, but I don't see a need for this feature. The stated purpose of the wrapper was to have an educational simple function for basic PCA, CA & PCO. Having _partialized_ PCA, CA & PCO is not such a simple educational case, but rather a special case of RDA, CCA & dbRDA, and could wait till you have advanced to these methods.

**Comment by jarioksa** [comment]
`stats::prcomp` and `stats::princomp` do have formula, but that is one-sided formula that is used to select variables for the analysis. It is a different kind of approach, and I think our kind of approach should be left to _constrained_ analysis instead of having an alternative and different formula for PCA.

**Comment by jarioksa** [comment]
I think this was settled: no wrapper. Please re-open if  you disagree, @gavinsimpson .
