### ISSUE TITLE
Problem with diversity in vegan package

### ISSUE THREAD

**Issue by Fra170197** [vegandevs/vegan#692]
Hello, 
if I run this code:   H <- diversity(abundances, index = "shannon")

an error appeares : Error in diversity(abundances, index = "shannon") : 
                                 unused argument (index = "shannon")

why? can someone help me?

**Comment by gavinsimpson** [comment]
Presumably some other package is loaded that provides a function `diversity()` that does not have an argument `index`. For future reference, to run the vegan version, use `vegan::diversity()` instead. If that works then something is masking the function and you'll have to figure that out; perhaps by printing `diversity` at the prompt and looking at the namespace it reports at the end.

**Comment by Fra170197** [comment]
Indeed I figured out that was the problem. Thanks for answering anyway :)

**Comment by jarioksa** [comment]
Looks like a duplicate of #608.
