### ISSUE TITLE
vegan package citation

### ISSUE THREAD

**Issue by UniAlberta** [vegandevs/vegan#702]
Hi, I used vegan pakage in late 2022 and 2023 for analyzing fungal communities. Unfortunately, I didn`t record the package version when I used it and now I need to mention it in my manuscript. Can you help me with that, please?

**Comment by psolymos** [comment]
You can check vegan package version against these CRAN last modified dates: <https://cran.r-project.org/src/contrib/Archive/vegan/>

**Comment by UniAlberta** [comment]
Thank you so much!
