### ISSUE TITLE
Error in ordConstrained(X, Y, Z, arg = scale, method = "rda") : dependent data and constraints must have the same number of rows

### ISSUE THREAD

**Issue by Coral4** [vegandevs/vegan#703]
Hi there, 

I am running an RDA with the following code: 
```r
rda(X, Y)
```
where X is a df containing the vectors of a Pcoa, and Y is a dataframe containing environmental variables. 
```r
dim(X) = 422 421
dim(Y) = 422 22
```
But I still get the following error: 
```r
Error in ordConstrained(X, Y, Z, arg = scale, method = "rda") : dependent data and constraints must have the same number of rows
```
Any thoughts would be appreciated! 

Best,
Coral

**Comment by jarioksa** [comment]
No idea. I cannot reproduce this.
