### ISSUE TITLE
bug in rda()

### ISSUE THREAD

**Issue by mut8** [vegandevs/vegan#94]
Hello,

I recently have problems with running the rda function (vegan version 2.0-7), even in datasets/scripts that worked in earlier versions. All attempts to use rda result in the error message 

```r
"Warning message:
In is.na(x$error.rate[1]) :
  is.na() applied to non-(list or vector) of type 'NULL'"
```

even though the same datasets compute easily with `cca()` or `princomp()` functions.

see example below 

thanks,
Lukas

```r
> data
                 F2B2   Gposneg  cy17prec
ER 1 2 L   0.90895926 0.3577752 0.3430286
ER 2 1 L   1.11370941 0.3557982 0.3400728
ER 3 1 L   0.95430094 0.3850514 0.3464962
GC NBW 2 L 1.08125909 0.3640970 0.5118545
GC NBE 1 L 0.49672687 0.4687129 0.4660554
GC O'R 1 L 0.71866998 0.4029527 0.5032395
ER 1 2 F   0.25949388 0.4377208 0.2837508
ER 2 1 F   0.31283615 0.3919091 0.2901602
ER 3 1 F   0.27872644 0.3930680 0.3054990
GC NBW 2 F 0.30475400 0.4553372 0.3621558
GC NBE 1 F 0.18854520 0.4689930 0.3740901
GC O'R 1 F 0.31850585 0.4845143 0.4645049
ER 1 2 H   0.12427040 0.3673476 0.4045438
ER 2 1 H   0.20619640 0.4336769 0.2231765
ER 3 1 H   0.10008428 0.3694892 0.3556774
GC NBW 2 H 0.17673029 0.3870191 0.3308577
GC NBE 1 H 0.12834551 0.4877205 0.3697912
GC O'R 1 H 0.18291568 0.4356605 0.4215446
ER 1 2 B   0.03497051 0.2322700 0.7843062
ER 2 1 B   0.02904011 0.3686987 0.7139940
ER 3 1 B   0.03024040 0.3768345 0.6292142
GC NBW 2 B 0.01942259 0.2897734 0.7365536
GC NBE 1 B 0.02849548 0.2792693 0.7661750
GC O'R 1 B 0.02954817 0.3244115 0.4464901

> princomp(data)
Call:
princomp(x = data)
Standard deviations:
    Comp.1     Comp.2     Comp.3 
0.34953160 0.15425761 0.04774404 
 3  variables and  24 observations.

> rda(data)
Call: 
rda(X = data)
Regularization parameters: 
NULL
Prior probabilities of groups: 
NULL
Misclassification rate: 
       apparent:  %
Warning message:
In is.na(x$error.rate[1]) :
  is.na() applied to non-(list or vector) of type 'NULL'

> cca(data)
Call: cca(X = data)
              Inertia Rank
Total          0.2447     
Unconstrained  0.2447    2
Inertia is mean squared contingency coefficient 
Eigenvalues for unconstrained axes:
    CA1     CA2 
0.20872 0.03603 

> R.version
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          0.2                         
year           2013                        
month          09                          
day            25                          
svn rev        63987                       
language       R                           
version.string R version 3.0.2 (2013-09-25)
nickname       Frisbee Sailing        
```

**Comment by gavinsimpson** [comment]
Can you supply the output from `sessionInfo()` *after* you've run your code and got the error, and show us what it says?

Basically the `rda()` you are running is not `vegan::rda()`; we don't have any regularisation parameters of anything like missclassification rates etc. Seems that `rda()` is doing a *regularised discriminants analysis* (which is why I know this is not a bug in **vegan**.

If you need **vegan** and the other package that has an `rda()` in it both loaded at the same time, you'll need to prefix the `rda()` call with the namespace for **vegan**, as in:

```r
vegan::rda(data)
```

FYI, if you can, update **vegan**; we are on version 2.2-1 now.

**Comment by mut8** [comment]
thanks for the prompt answer, that solved the problem. Also, thanks for your great work, I'm using vegan for 5+ years now and it was key to much of my data analysis!

cheers, Lukas

The error occured only after loading the package 'agricolae'.

here's the sussion list
> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] stats4    splines   grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] nlme_3.1-113       multcomp_1.3-8     TH.data_1.0-6      tables_0.7.79      car_2.0-22         lme4_1.1-7        
 [7] Rcpp_0.11.3        Matrix_1.1-2       plotrix_3.5-10     xtable_1.7-4       multcompView_0.1-5 lawstat_2.4.1     
[13] VGAM_0.9-6         mvtnorm_1.0-2      agricolae_1.2-1    TeachingDemos_2.9  gplots_2.16.0      Hmisc_3.14-6      
[19] Formula_1.1-2      survival_2.37-7    lattice_0.20-29    MASS_7.3-37        vegan_2.0-7        permute_0.8-3     

loaded via a namespace (and not attached):
 [1] acepack_1.3-3.3     bitops_1.0-6        boot_1.3-9          caTools_1.14        cluster_1.14.4     
 [6] coda_0.16-1         combinat_0.0-8      deldir_0.1-7        foreign_0.8-59      gdata_2.13.3       
[11] gtools_3.4.1        KernSmooth_2.23-10  klaR_0.6-12         latticeExtra_0.6-26 LearnBayes_2.15    
[16] minqa_1.2.4         nloptr_1.0.4        nnet_7.3-7          RColorBrewer_1.1-2  rpart_4.1-5        
[21] sandwich_2.3-2      sp_1.0-17           spdep_0.5-82        tools_3.0.2         zoo_1.7-11

**Comment by gavinsimpson** [comment]
Thanks for the confirmation. Glad you're finding **vegan** useful!

**Comment by GZikalala** [comment]
Hi, 

Hello,

I have a problems with running the rda function (vegan version 2.4-1), 

vegan::rda(Y ~ X1 + X2, X3, X4, data= Env_1dmod)

"Error in formula.default(object, env = baseenv()) : invalid formula"

Help will be much appreciated. 

Thanks.

Gugu

**Comment by gavinsimpson** [comment]
@GZikalala please start a new thread in future, rather than jump on an old one.

But for now, realise that you don't normally put `,` in a formula. If you want a constrained mode with the four `X` variates then you want

```r
rda(Y ~ X1 + X2 + X3 + X4, data= Env_1dmod)
```

This is in line with most other modelling functions that I am aware of in R.

**Comment by GZikalala** [comment]
Gavin,

I will be sure to start a new thread. but note that i do have + instead of commas, i made a typo in this thread.  So my input as yours and the same error arises:
rda(Y ~ X1 + X2 + X3 + X4, data= Env_1dmod)
